Make tools more human-friendly.
* tools/bin/slr.in,
* tools/bin/slc.in: Bark if a command-line parameter that requires
an argument appears last (without its argument) on the
command-line.

* tools/bin/cce.in,
* tools/bin/slc.in,
* tools/bin/slt.in,
* tools/bin/slr.in,
* tools/lib/r-host.sh,
* tools/lib/r-mtalpha-sim.sh.in,
* tools/lib/r-mtsparc-sim.sh.in: Print only the short utility name
in warning and error messages, instead of the full path.

diff --git a/tools/bin/cce.in b/tools/bin/cce.in
--- a/tools/bin/cce.in
+++ b/tools/bin/cce.in
@@ -37,7 +37,7 @@ CC_MTSPARC=$UTCC_MTSPARC
 version=@slc_version@
 slrev=@slc_revision@
 bugreports=@bugreports@
-
+basename=${0##*/}
 
 do_usage() {
     cat <<EOF
@@ -103,7 +103,7 @@ do_timestamp() {
 }
 
 die() {
-    echo "$0:" "$@" >&2
+    echo "$basename:" "$@" >&2
     exit 1
 }
 
@@ -118,7 +118,7 @@ for arg in "$@"; do
 	-t|--timestamp) do_timestamp ;;
 	-s|--set-vars) set_vars=1 ;;
 	-h|--help) do_usage;;
-	-*) echo "$0: unrecognized command-line argument: $arg (try -h)" >&2; exit 1;;
+	-*) echo "$basename: unrecognized command-line argument: $arg (try -h)" >&2; exit 1;;
 	*) alias=$arg
     esac
 done
@@ -215,7 +215,7 @@ for d in $slc_datadir; do
   fi
 done
 if test -z "$found"; then
-   echo "$0: warning: could not find t-$slc_transbase in $slc_datadir" >&2
+   echo "$basename: warning: could not find t-$slc_transbase in $slc_datadir" >&2
 else
     slc_trans=$found
     slc_tflags="$slc_tflags -I$slc_trans"
@@ -231,7 +231,7 @@ for m4_preinc in slc_m4sugar.m4 slc.m4; do
      fi
    done
    if test -z "$found"; then
-      echo "$0: warning: could not find $m4_preinc in $slc_incdir" >&2
+      echo "$basename: warning: could not find $m4_preinc in $slc_incdir" >&2
    else
       slc_tflags="$slc_tflags $found"
    fi
@@ -251,7 +251,7 @@ case $slc_dialect-$slc_arch in
 	case $slc_complang in
 	    cpp) slc_compiler=$CXX ;;
 	    c)   slc_compiler="$CC" ;;
-	    utc) echo "$0: warning: no compiler for $dialect-$arch" >&2 ;;
+	    utc) echo "$basename: warning: no compiler for $dialect-$arch" >&2 ;;
 	esac
 	slc_filter=cp
 	;;
@@ -323,7 +323,7 @@ case $slc_os in
 		fi
             done
 	    if test -z "$found"; then
-		echo "$0: warning: slrt.o not found for $slc_arch-$slc_os in $slc_libdir" >&2
+		echo "$basename: warning: slrt.o not found for $slc_arch-$slc_os in $slc_libdir" >&2
             else
 		slc_ldflags="$slc_ldflags $found"
 	    fi
diff --git a/tools/bin/slc.in b/tools/bin/slc.in
--- a/tools/bin/slc.in
+++ b/tools/bin/slc.in
@@ -21,7 +21,7 @@ root=$(cd $(dirname "$0"); pwd)
 timeout=$root/timeout
 TIMEOUT=${TIMEOUT:-10000}; export TIMEOUT
 cce_helper=${CCE:-@cce_helper@}
-basename=${0#*/}
+basename=${0##*/}
 TMPDIR=${TMPDIR:-/tmp}
 
 version=@slc_version@
@@ -68,16 +68,16 @@ M4=${M4:-@M4@}
 cleanup() {
   for f in $inflight $tempfiles $tempdirs; do
     if test -z "$keep"; then 
-      test -n "$verbose" && echo "$0: $f: deleting temporary" >&2
+      test -n "$verbose" && echo "$basename: $f: deleting temporary" >&2
       if test -d "$f"; then 
 	  if ! rmdir "$f" ; then
-	      echo "$0: $f: warning: could not delete directory" >&2
+	      echo "$basename: $f: warning: could not delete directory" >&2
 	  fi
       else 
 	  rm -f "$f"
       fi
     else
-      test -e "$f" && echo "$0: $f: left over temporary" >&2
+      test -e "$f" && echo "$basename: $f: left over temporary" >&2
     fi
   done
   inflight=
@@ -87,13 +87,13 @@ cleanup() {
 trap cleanup 0 ERR HUP INT TERM QUIT
 
 die() {
-    echo "$0:" "$@" >&2
+    echo "$basename:" "$@" >&2
     exit 1
 }
 
 check_exists() {
   if ! test -e "$1"; then
-     echo "$0: $1: No such file or directory" >&2
+     echo "$basename: $1: No such file or directory" >&2
      return 1
   fi
   return 0
@@ -147,11 +147,11 @@ for arg in "$@"; do
       -D*|-U*|-C*|-H)  extra_ppflags="$extra_ppflags $arg" ;;
 
       -MG|-MP|-MD|-MMD)
-                echo "$0: warning: $arg ignored" >&2;;
+                echo "$basename: warning: $arg ignored" >&2;;
       -MT|-MQ)
-                echo "$0: warning: $arg ignored" >&2; followaction=ignore ;;
+                echo "$basename: warning: $arg ignored" >&2; followaction=ignore ;;
       -MF)
-                echo "$0: warning: $arg ignored" >&2; followaction=touch ;;
+                echo "$basename: warning: $arg ignored" >&2; followaction=touch ;;
 
       -I*)           extra_inc="$extra_inc $arg" ;;
       -Wa,*)         extra_asflags="$extra_asflags $arg" ;;
@@ -163,7 +163,7 @@ for arg in "$@"; do
 
       -x|-M|-MM)  die "$arg not supported yet" ;;
       -nostdinc*) 
-                echo "$0: warning: $arg may not behave as expected" >&2
+                echo "$basename: warning: $arg may not behave as expected" >&2
                 extra_ppflags="$extra_ppflags $arg"
                 ;;
       -mutc*)   die "-mutc is deprecated, use -b instead" ;;
@@ -190,6 +190,8 @@ for arg in "$@"; do
       *) check_exists "$arg" && in_ld_spec="$in_ld_spec $arg";;
   esac
 done
+if test -n "${prev_arg:-}"; then die "argument to \`$arg' is missing"; fi
+   
 
 # Special actions that do not require processing
 if test "x$slc_mode" = xdisplay_version; then
@@ -575,7 +577,7 @@ prepare_chain() {
 	fi
     else
 	for f in $specfiles; do
-	    echo "$0: $f: $phrase input file unused because $phrase not run" >&2
+	    echo "$basename: $f: $phrase input file unused because $phrase not run" >&2
 	done
     fi
 }
diff --git a/tools/lib/r-mtsparc-sim.sh.in b/tools/lib/r-mtsparc-sim.sh.in
--- a/tools/lib/r-mtsparc-sim.sh.in
+++ b/tools/lib/r-mtsparc-sim.sh.in
@@ -2,6 +2,7 @@
 # $Id$
 set -eu
 MGSIM_SPARC=${MGSIM_SPARC:-@MGSIM_SPARC@}
+basename=${0##*/}
 program=${1:?}
 datafile=${2:?}
 fdatafile=${3:?}
@@ -10,21 +11,21 @@ shift
 shift
 shift
 if ! test -x "$program"; then
-    echo "$0: $program: not an executable" >&2
+    echo "$basename: $program: not an executable" >&2
     exit 1
 fi
 if ! test -r "$datafile"; then
-    echo "$0: $datafile: file not found or not readable" >&2
+    echo "$basename: $datafile: file not found or not readable" >&2
     exit 1
 fi
 
 if ! test -r "$fdatafile"; then
-    echo "$0: $fdatafile: file not found or not readable" >&2
+    echo "$basename: $fdatafile: file not found or not readable" >&2
     exit 1
 fi
 
 if ! "$MGSIM_SPARC" --help >/dev/null 2>&1; then
-  echo "$0: cannot find simulator (MGSIM_SPARC=$MGSIM_SPARC)." >&2
+  echo "$basename: cannot find simulator (MGSIM_SPARC=$MGSIM_SPARC)." >&2
   exit 1
 fi
 
@@ -38,6 +39,6 @@ if test -n "${DEBUG:-}"; then
    do_debug=$DEBUGGER
 fi
 if test -n "${VERBOSE:-}"; then
-   echo "$0: running: ${RUNNER_PREFIX:-} $do_debug $MGSIM_SPARC ${SIMARGS:-} -t $* -L16 $datafile -L17 $fdatafile $program" >&2
+   echo "$basename: running: ${RUNNER_PREFIX:-} $do_debug $MGSIM_SPARC ${SIMARGS:-} -t $* -L16 $datafile -L17 $fdatafile $program" >&2
 fi  
 exec ${RUNNER_PREFIX:-} $do_debug $MGSIM_SPARC ${SIMARGS:-} -t "$@" -L16 "$datafile" -L17 "$fdatafile" "$program"
