Sanitize scripts. Simplify code, ease debugging.
* tools/bin/timeout.in,
* tools/bin/slc.in,
* tools/bin/slr.in,
* tools/bin/slt.in: Enable shell tracing (`set -x') when
env. var. TRACE is set (used for debugging).

* doc/HACKING.txt: Document the feature.

* tools/bin/timeout.in: Major redesign to simplify and get signal
management and exit codes right. Processes now killed gracefully
(SIGTERM) once before SIGKILL.

* tools/bin/slt.in: Detect SIGTERM in child as timeout.

* tools/bin/slr.in: Use similar process management as in
`timeout'. The cleanup now happens in a background process instead
of a trap. Document the different steps.

* tools/bin/slc.in: Use `timeout' to start compiler sub-processes,
so that they get terminated eventually when run from `slt' with
TIMEOUT set. Trap on SIGHUP as well.
* tools/bin/slt.in: Do not prefix `timeout' to `slc', since `slc'
takes care of aborting on its own.

* tools/lib/r-host.sh,
* tools/lib/r-mtalpha-sim.sh.in,	
* tools/lib/r-mtsparc-sim.sh.in: Protect with `set -u' against
bugs. Update variable accesses accordingly.

* tools/bin/slt.in: Do not dump logs when terminating due to
signal. List remaining files in all cases. Support .S as a test
extension.

diff --git a/tools/bin/slr.in b/tools/bin/slr.in
--- a/tools/bin/slr.in
+++ b/tools/bin/slr.in
@@ -1,5 +1,5 @@
 #! @BASH@
-#
+# -*- mode: shell-script -*-
 # slr: This file is part of the SL toolchain.
 #
 copyright="Copyright (C) 2009 The SL project."
@@ -14,17 +14,20 @@ copyright="Copyright (C) 2009 The SL project."
 #
 # $Id$
 #
-set -e
+PS4='+ slr($$): '
+if test -n "${TRACE:-}"; then set -x; fi
+set -eu
 python=${PYTHON:-@python@}
 slc_helper=${SLC:-@slc_helper@}
 sag_helper=${SAG:-@sag_helper@}
 slc_libdir=${SLC_LIBDIR:-@slc_libdir@}
 slc_datadir=${SLC_DATADIR:-@slc_datadir@}
 TMPDIR=${TMPDIR:-/tmp}
+KEEP=${KEEP:-}
 
 version=@slc_version@
 slrev=@slc_revision@
-bugreports=@bugreports@
+bugreports="@bugreports@"
 
 do_usage() {
   cat <<EOF
@@ -150,6 +153,7 @@ die() {
 }
 
 # Command line analysis
+runner=
 prev_arg=
 show_embedded=
 vars=
@@ -215,6 +219,7 @@ if ! test -x "$program"; then
   die 126 "permission denied: $program"
 fi
 
+# detect runner & print string if requested
 if test -n "$show_embedded" -o -z "$runner"; then
   tag=$(strings "$program"|grep '^slr_runner:.*:'|tail -n1|cut -d: -f2)
   if test "x$tag" = "x"; then
@@ -235,7 +240,6 @@ if test "x$datatag" = "x"; then
     die 1 "can't determine cce tag to recompile"
 fi
 
-
 if test -z "$runner"; then
   # Not specified, use tag if found
   if test -n "$tag"; then
@@ -245,7 +249,7 @@ if test -z "$runner"; then
   fi
 fi
 
-# check it
+# search the runner in the libdirs
 runner_script=
 saveIFS=$IFS
 IFS=:
@@ -259,6 +263,7 @@ if test -z "$runner_script"; then
     die 1 "$runner: cannot find runner script"
 fi
 
+# search arggen.sl in the datadirs
 arggen=
 for d in $slc_datadir; do
     if test -r "$d/arggen.sl"; then
@@ -271,30 +276,7 @@ if test -z "$arggen"; then
     die 1 "arggen.sl not found in $slc_datadir"
 fi
 
-cleanfiles=
-docleanup() {
-    for f in $cleanfiles; do
-	if test -z "$KEEP"; then
-	    rm -rf "$f" >/dev/null 2>&1
-	else
-	    echo "$0: $f: left over temporary" >&2
-	fi
-    done
-}
-
-trapcleanup() {
-    local sig
-    sig=$1
-    docleanup
-    trap - INT PIPE TERM QUIT ALRM
-    kill -$sig $$
-}
-errcleanup() {
-    docleanup
-    trap - ERR
-    exit 1
-}
-
+# if a slrvars cache file is specified, use it
 if test -n "$rdatafile"; then
   if ! test -r "$rdatafile"; then die 1 "$rdatafile: cannot read file"; fi
   if test -n "$vars"; then 
@@ -306,6 +288,7 @@ else
   dodata=1
 fi
 
+# if a fibre cache file is specified, use it
 if test -n "$rfdatafile"; then
   if ! test -r "$rfdatafile"; then die 1 "$rfdatafile: cannot read file"; fi
   if test -n "$vars"; then 
@@ -317,20 +300,34 @@ else
   dofdata=1
 fi
 
-trap 'trapcleanup INT' INT
-trap 'trapcleanup PIPE' PIPE
-trap 'trapcleanup TERM' TERM
-trap 'trapcleanup QUIT' QUIT
-trap 'trapcleanup ALRM' ALRM
-trap 'errcleanup' ERR
-
+# if the cache(s) don't yet exist, create a temporary
+# directory for the data generation processes. This
+# needs to be erased when `slr' and its child processes
+# are terminated somehow and KEEP is not set, so start
+# a background watchdog for this purpose.
 if test -n "$dodata" -o -n "$dofdata"; then
     # build temporary directory
     baseout=$(basename "$program")
-    tmpdir=$(mktemp -d $TMPDIR/"$baseout".XXXXXXXX)
-    cleanfiles=$tmpdir
+    tmpdir=$(mktemp -d $TMPDIR/"$baseout".slr-XXXXXXXX)
+    if test -n "$KEEP"; then
+	echo "$0: $tmpdir: will not delete after program termination" >&2
+    else
+	SLR_PID=$$
+	(
+	    # start watchdog
+	    PS4='+ slr-wd($$)'
+	    while true; do 
+		if ! kill -0 $SLR_PID 2>/dev/null; then
+		    rm -rf "$tmpdir" >/dev/null 2>&1
+		    exit 0
+		fi
+		sleep 1
+	    done
+	    ) & 
+    fi
 fi
 
+# do we need to prepare the slrvars data file?
 if test -n "$dodata"; then
     if test -n "$wdatafile"; then
 	datafile=$wdatafile
@@ -344,28 +341,36 @@ if test -n "$dodata"; then
 	$python "$sag_helper" d list <"$tmpdir"/args.spec
 	exit 0
     fi
-      
+
+    # does the program take any slr vars?
     if test -s "$tmpdir"/args.spec; then
+
+	# prepare C struct with slr var data
 	if test -n "$VERBOSE"; then
 	    echo "$0: running: $python $sag_helper d $vars <$tmpdir/args.spec >$tmpdir/data.c" >&2
 	fi
 	$python "$sag_helper" d $vars <"$tmpdir"/args.spec >"$tmpdir"/data.c
-	
+
+	# compile arggen.sl with slr var data in C
 	mkdir -p "$tmpdir"/slc-rec
 	if test -n "$VERBOSE"; then
 	    echo "$0: running: TMPDIR=$tmpdir/slc-rec @BASH@ $slc_helper -b $datatag -o $tmpdir/gen.x -I$tmpdir $arggen" >&2
 	fi
 	TMPDIR="$tmpdir"/slc-rec @BASH@ "$slc_helper" -b "$datatag" -o "$tmpdir"/gen.x -I"$tmpdir" "$arggen"
+
+	# run slr recursively on the arggen binary to dump the data
 	mkdir -p "$tmpdir"/slr-rec
 	if test -n "$VERBOSE"; then
 	    echo "$0: running: TMPDIR=$tmpdir/slr-rec @BASH@ $0 $tmpdir/gen.x >$datafile" >&2
 	fi
 	TMPDIR="$tmpdir"/slr-rec @BASH@ "$0" "$tmpdir"/gen.x -Ws,-q,-o,NumProcessorsPerFPU=1 -n 1 >"$datafile"
     else
+	# just ensure the cache file exists 
         true >"$datafile"
     fi
 fi
 
+# do we need to prepare the fibre data file?
 if test -n "$dofdata"; then
     if test -n "$wfdatafile"; then
 	fdatafile=$wfdatafile
@@ -373,55 +378,51 @@ if test -n "$dofdata"; then
 	fdatafile="$tmpdir"/fdata
     fi
     
+    # was a Fibre file specified?
     if test -n "$fibre_in"; then
 	if test "x$fibre_in" != "x-" -a \! -r "$fibre_in"; then 
-	    docleanup; die 1 "$fibre_in: cannot read file"
+	    die 1 "$fibre_in: cannot read file"
 	fi
 
-        # check program parameters
+        # transform the Fibre data to a C string definition
 	if test -n "$VERBOSE"; then
 	    echo "$0: running: [sed] <$fibre_in |$python $sag_helper f >$tmpdir/fdata.c" >&2
 	fi
-
 	(if test "x$fibre_in" = "x-"; then cat; else cat "$fibre_in"; fi) | \
 	    sed -e 's/\#.*//g;' | \
-	    (tr '\n' ' ';echo " None") | \
+	    (tr '\t\n' '  ';echo " None") | \
 	    sed -e 's/^ *//g;
 s/\[[0-9 ,]*: */\[/g;
 s/ *\]/\]/g;
 s/  */,/g;
-s/d0//g;
+s/[dD]/e/g;
 s/,$//g' | $python "$sag_helper" f >"$tmpdir"/fdata.c
 	
+	# compile arggen.sl with Fibre data in C
 	mkdir -p "$tmpdir"/slc-rec
 	if test -n "$VERBOSE"; then
 	    echo "$0: running: TMPDIR=$tmpdir/slc-rec @BASH@ $slc_helper -b $datatag -o $tmpdir/gen.x -I$tmpdir -DFIBRE_DATA=1 $arggen" >&2
 	fi
 	TMPDIR="$tmpdir"/slc-rec @BASH@ \
 	    "$slc_helper" -b "$datatag" -o "$tmpdir"/gen.x -I"$tmpdir" -DFIBRE_DATA=1 "$arggen"
+
+	# run slr recursively on the arggen binary to dump the data
 	mkdir -p "$tmpdir"/slr-rec
 	if test -n "$VERBOSE"; then
 	    echo "$0: running: TMPDIR=$tmpdir/slr-rec @BASH@ $0 $tmpdir/gen.x >$fdatafile" >&2
 	fi
 	TMPDIR="$tmpdir"/slr-rec @BASH@ "$0" "$tmpdir"/gen.x -Ws,-q,-o,NumProcessorsPerFPU=1 -n 1 >"$fdatafile"
     else
-	# Ensure a tag = -1 for the first item
+	# Ensure a tag = -1 for the first Fibre item
         printf '\xff\xff\xff\xff\xff\xff\xff\xff' >"$fdatafile"
     fi
 fi
 
-if test -n "$preponly"; then docleanup; exit 0; fi
+# cache only?
+if test -n "$preponly"; then exit 0; fi
 
 export SIMARGS VERBOSE DEBUG NCORES
 if test -n "$VERBOSE"; then
     echo "$0: running: @BASH@ $runner_script $program $datafile $fdatafile" >&2
 fi
-@BASH@ "$runner_script" "$program" "$datafile" "$fdatafile"
-
-docleanup
-
-trap - ERR
-
-# Local variables:
-# mode: shell-script
-# End:
+exec @BASH@ "$runner_script" "$program" "$datafile" "$fdatafile"
diff --git a/tools/bin/slt.in b/tools/bin/slt.in
--- a/tools/bin/slt.in
+++ b/tools/bin/slt.in
@@ -14,8 +14,10 @@ copyright="Copyright (C) 2009 The SL project."
 #
 # $Id$
 #
-
+PS4='+ slt($$): '
+if test -n "$TRACE"; then set -x; fi
 set -e
+
 basename=$(basename "$0")
 root=$(cd $(dirname "$0"); pwd)
 
@@ -340,6 +342,7 @@ testsrc=$1
 
 case $1 in
   *.sl)     testname=$(basename "$1" .sl);;
+  *.S)      testname=$(basename "$1" .S);;
   *.s)      testname=$(basename "$1" .s);;
   *)
   cat <<EOF
@@ -371,7 +374,7 @@ check_status() {
     if test $1 = 127; then status=invcmd
     elif test $1 = 0; then status=ok
     elif test $1 -lt 127; then status=error; errcode=$1
-    elif test $1 = 137; then status=timeout
+    elif test $1 = 143 -o $1 = 137; then status=timeout
     else status=signal; signal=$(expr $1 - 128)
     fi
     if test $status = signal; then echo "Terminated with signal $signal" >&2; fi
@@ -498,7 +501,7 @@ do_compile() {
   local offset command x
   offset=$1
   echo "===== TEST: $testsrc, COMPILE ======" >$baseout.log
-  command="$timeout $slc -v -t $outdir -b $impl -o $baseout.x $testsrc $COMPILE_ARGS"
+  command="$slc -v -t $outdir -b $impl -o $baseout.x $testsrc $COMPILE_ARGS"
   echo "$command" >>$baseout.log
   set +e
   KEEP=1 TIMEOUT=60 $command >>$baseout.log 2>&1
@@ -525,7 +528,7 @@ do_run() {
 	  command=$(echo "$timeout $runner -t $baseout.x ${vars[*]} $RUN_ARGS"|sed -e "s|TEST|$testsrc|g")
 	  echo "$command >>$baseout.out" >>$baseout.log
 	  set +e
-	  $command >>$baseout.out 2>>$baseout.log 
+	  $command >>$baseout.out 2>>$baseout.log
 	  x=$?
 	  set -e
 	  
@@ -616,14 +619,16 @@ do_preptest() {
 	die "$outdir: directory is not writable"
     fi
     export TMPDIR="$outdir"
+    logs="$logs $baseout.log"
+    basenames="$basenames $baseout"
 }
 
 
 # start testing
 counter=0
 logs=
+basenames=
 do_preptest "$impl1"
-logs="$logs $baseout.log"
 
 prefign=${XIGNORE:-*x:*}
 xfailpats=$(grep "XFAIL:" <"$testsrc"|sed -e 's/^.*XFAIL:\(.*\)$/\1/g')
@@ -665,9 +670,11 @@ else
     colspertest=1
 fi
 
-bye() {
+sighandle() {
   local sig
   sig=$1
+  echo >&2
+  echo "Signal received (SIG$sig)!" >&2
   for pid in $towait; do
     kill $pid >/dev/null 2>&1
   done
@@ -675,17 +682,16 @@ bye() {
 }
 
 check_proc() {
-    local x
+    local x b bf
     x=$1
     if test -n "$signalled"; then 
-        echo >&2
-	echo "Signal received (SIG$signalled)!" >&2
-	trap - INT QUIT HUP TERM PIPE
-	for l in $logs; do
-	    if test -r "$l"; then 
-		echo "$0: failure log: $l" >&2
-		if test -n "$DUMP_LOGS"; then cat "$l" >&2; echo >&2; fi
-	    fi
+	trap - INT QUIT HUP ALRM TERM PIPE
+	for b in $basenames; do
+	    for bf in $b.*; do
+		if test -e "$bf"; then
+		    echo "$basename: left over: $bf" >&2
+		fi
+	    done
 	done
 	kill -$signalled $$
 	exit 128
@@ -700,15 +706,16 @@ fail=0
 # since output will be used as reference:
 
 signalled=
-trap "bye INT" INT
-trap "bye QUIT" QUIT
-trap "bye HUP" HUP
-trap "bye TERM" TERM
-trap "bye PIPE" PIPE
+trap "sighandle INT" INT
+trap "sighandle QUIT" QUIT
+trap "sighandle HUP" HUP
+trap "sighandle TERM" TERM
+trap "sighandle ALRM" ALRM
+trap "sighandle PIPE" PIPE
 do_check $impl $offset &
 towait=$!
 set +e
-wait $towait
+wait $towait >/dev/null 2>&1
 x=$?
 set -e
 towait=
@@ -720,12 +727,11 @@ refout=$baseout.out
 for impl1 in "$@"; do
     offset=$(expr $offset + $colspertest)
     do_preptest "$impl1"
-    logs="$logs $baseout.log"
     do_check $impl $offset "$refout" &
     towait="$towait $!"
     if test -n "$SEQUENTIAL"; then
 	set +e
-	wait $towait
+	wait $towait >/dev/null 2>&1
 	x=$?
 	set -e
 	towait=
@@ -736,7 +742,7 @@ done
 if test -z "$SEQUENTIAL"; then
     for w in $towait; do
 	set +e
-	wait $w
+	wait $w >/dev/null 2>&1
 	x=$?
 	set -e
 	check_proc $x
@@ -765,9 +771,16 @@ if test $fail = 0 -a -z "$KEEP"; then
 else
     for l in $logs; do
 	if test -r "$l"; then 
-	    echo "$0: failure log: $l" >&2
+	    echo "$basename: failure log: $l" >&2
 	    if test -n "$DUMP_LOGS"; then cat "$l" >&2; echo >&2; fi
 	fi
+    done
+    for b in $basenames; do
+	for bf in $b.*; do
+	    if test -e "$bf"; then
+		echo "$basename: left over: $bf" >&2
+	    fi
+	done
     done
 fi
 exit $fail
