Sanitize test suite. Make `slt' output more human-friendly.
The tool `slt' would create output directories for log files and
temporary files as direct sub-directories of the current directory
always, with directories numbered after the test output
columns (e.g. `___tests_0'). This would make the test output
difficult to find when the input test (.sl) was located in a
relative path. This was changed so that test output directories
carry the name of the SL implementation being tested, and are
structured in a hierarchy similar to the input test, possibly the
same if building from the source tree directly (e.g. `tests/_seqc').

The tool `slt-many' would pick up `slt' from PATH always, instead
of the build directory as the other tools, resulting in `make
check-slt' failing before the tools are installed in PATH or `eval
$(make show-vars)' is run. This was fixed by handling tool
locations like the other tools.

* tools/bin/Makefile.am,
* sl.mk: Introduce new tool location variable for `slt'.
	
* tools/bin/slt-many: Rename to...	
* tools/bin/slt-many.in: here. Handle copyright, bug reporting,
version handling, tool locations, TRACE and PS4 like the other
tools.

* tools/bin/slt.in: Handle $SRCDIR. Document it.

* tests.mk: Indicate $SRCDIR to `slt'. Set tool locations before
invoking `slt-many'.

diff --git a/tools/bin/slt-many.in b/tools/bin/slt-many.in
--- a/tools/bin/slt-many.in
+++ b/tools/bin/slt-many.in
@@ -1,11 +1,29 @@
-#! /bin/sh
-version=2
-
+#! @BASH@
+# -*- mode: shell-script -*-
+# slc: This file is part of the SL toolchain.
+#
+copyright="Copyright (C) 2009 The SL project."
+#
+# This program is free software; you can redistribute it and/or
+# modify it under the terms of the GNU General Public License
+# as published by the Free Software Foundation; either version 3
+# of the License, or (at your option) any later version.
+#
+# The complete GNU General Public Licence Notice can be found as the
+# `COPYING' file in the root directory.
+#
+# $Id$
+#
+PS4='+ slt-many($$): '
+if test -n "$TRACE"; then set -x; fi
 set -e
-rev='$Rev$'
-rev=$(echo "$rev"|cut -d' ' -f2)
+
+version=@slc_version@
+slrev=@slc_revision@
 root=$(dirname "$0")
 basename=$(basename "$0")
+bugreports=@bugreports@
+slt=${SLT:-@slt_helper@}
 
 if test $# = 0; then
    tests=$(find . -name '*.sl'|grep -v '/_'|sort)
@@ -62,17 +80,20 @@ Diagnostics:
 
   1                  Some test(s) failed.
 
-Report bugs and suggestions to the CSA Trac issue tracker, or to
-<sl-users@nic.surfnet.nl>.
+Report bugs and suggestions to $bugreports.
 EOF
    exit 0
 elif test "$1" = "-v" -o "$1" = "--version"; then
+    rev='$Rev$'
+    rev=$(echo "$rev"|cut -d' ' -f2)
    cat <<EOF   
-$basename $version.$revision
+$basename $version (rev $slrev/$rev)
 
-Copyright (C) 2008, 2009 the CSA group - The SL project
+$copyright
+This is free software; see the source for copying conditions.  There is NO
+warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
 
-Script written by Raphael Poss, with input from Mike Lankamp,
+Script written by Raphael 'kena' Poss, with input from Mike Lankamp,
 Thomas Bernard, Simon Polstra.
 EOF
    exit 0
@@ -95,8 +116,8 @@ else
   done
 fi
 
-if ! slt --version >/dev/null 2>&1; then
-  echo "\`slt' not found in PATH, cannot run." >&2
+if ! $slt --version >/dev/null 2>&1; then
+  echo "\`$slt' not found or not executable, cannot run. (maybe set PATH or SLT?)" >&2
   exit 1
 fi
 
@@ -111,8 +132,8 @@ SLT_IMPL_LIST=${SLT_IMPL_LIST:-seqc ptl ppp utc0}
 echo "The following implementation(s) are tested:"
 for impl in $SLT_IMPL_LIST; do
     name=$(echo "$impl"|cut -d: -f1)
-    flag=$(echo "$impl"|cut -d: -f2|tr '~' ' ')
-    run=$(echo "$impl"|cut -d: -f3|tr '~' ' ')
+    flag=$(echo "$impl::"|cut -d: -f2|tr '~' ' ')
+    run=$(echo "$impl::"|cut -d: -f3|tr '~' ' ')
     printf '\t%s\t' $name
     if test x != "x$flag"; then
 	printf '(slc %s) ' "$flag"
@@ -137,7 +158,7 @@ export SLT_IMPL_LIST
 trap report INT TERM QUIT HUP
 for t in $tests; do
   set +e
-  slt "$t"
+  $slt "$t"
   x=$?
   set -e
   count=$(expr $count + 1)
