First "working" implementation of parameter passing for SL programs.
* bin/sag: Use C syntax instead of assembly for data source
code. Fix case where an empty list is specified as
initializer. Print help on standard error.

* lib/arggen.sl: Add.

* include/sgr.slh: Add.

* bin/sgr.in: Better error handling. Compute data source file
based on command line, `sag' and the sgr specifiers in the program
binary from `sgr.slh'. Use `sgr_datatag' in binary as arch name to
compile data source file and `arggen.sl', then recurse to generate
the data. Define parameter -Ws to pass arguments to simulator.

* lib/host-host-seqc/slrt.c,
* lib/host-host-ptl/slrt.c,	
* lib/mtalpha-sim/slrt.s: Define "sgr_datatag" in output binary.

* include/svp/io.slh: Declare svp_io_write, required for
arggen.sl.
* include/svp/iomacros.slh: Wrap it.
* lib/svplib/io.sl: Implement it.
* lib/Makefile.am: Update accordingly.

* lib/r-host/run.sh,	
* lib/mtalpha-sim/run.sh.in: Recognize data file. Better error
handling.

* bin/Makefile.am: Distribute / install `sag'.
* tests.mk: Overload SAG during tests.
* doc/acronyms.txt: Document `sag'.

* lib/host-host-seqc/load.c: Add missing file from 2 previous commits.

* demo/fibonacci.sl: Use the new parameter system.

* demo/fft.sl: Use the new parameter system. Allow to skip
printing the data after the computation based on the value of
parameters Pi (print ints) and Pf (print floats).

* demo/testfft.sh: Add script to benchmark the fft, based on the
new parameter system.
* demo/Makefile.am: Update accordingly.

* lib/div: Kill, as is now unused.
* bin/cce.in: Better handling of unknown tags.

* bin/spp: Bug fix thanks to fibo & fft: remove FP/RA spill in
function prologue. This provides (some) support for C99's VLAs.

diff --git a/bin/cce.in b/bin/cce.in
--- a/bin/cce.in
+++ b/bin/cce.in
@@ -165,17 +165,20 @@ basearch=$(echo "$slc_arch"|cut -c3-)
 basearchvar=$(echo "$basearch"|tr a-z A-Z)
 
 # Language mode selection
+slc_complang=unknown
 case $slc_dialect in
     ptl*)     slc_complang=cpp;;
     seqc|ppp) slc_complang=c;;
     utc*)     slc_complang=utc;;
-    *) 
+    *) echo "unknown dialect: $slc_dialect" >&2;;
 esac
 
 # Transformation selection
+slc_transbase=unknown
 case $slc_dialect-$slc_arch in
     utc*|seqc*|ptl*) slc_transbase=$slc_dialect	;;
     ppp-*)     slc_transbase=ppp$basearch ;;
+    *) echo "unknown combination: $slc_dialect-$slc_arch" >&2;;
 esac
 
 save_IFS=$IFS
@@ -188,11 +191,12 @@ for d in $slc_datadir; do
   fi
 done
 if test -z "$found"; then
-   die "could not find t-$slc_transbase in $slc_datadir"
+   echo "$0: warning: could not find t-$slc_transbase in $slc_datadir" >&2
+else
+    slc_trans=$found
+    slc_tflags="$slc_tflags -I$slc_trans"
+    slc_ppflags="$slc_ppflags -I$slc_trans/include"
 fi
-slc_trans=$found
-slc_tflags="$slc_tflags -I$slc_trans"
-slc_ppflags="$slc_ppflags -I$slc_trans/include"
 
 for m4_preinc in slc_m4sugar.m4 slc.m4; do
    found=
@@ -203,9 +207,10 @@ for m4_preinc in slc_m4sugar.m4 slc.m4; do
      fi
    done
    if test -z "$found"; then
-      die "could not find $m4_preinc in $slc_incdir"
+      echo "$0: warning: could not find $m4_preinc in $slc_incdir" >&2
+   else
+      slc_tflags="$slc_tflags $found"
    fi
-   slc_tflags="$slc_tflags $found"
 done
 for d in $slc_incdir; do
   slc_tflags="$slc_tflags -I$d"
@@ -222,7 +227,7 @@ case $slc_dialect-$slc_arch in
 	case $slc_complang in
 	    cpp) slc_compiler=$CXX ;;
 	    c)   slc_compiler="$CC" ;;
-	    utc) die "no compiler for $dialect-$arch" ;;
+	    utc) echo "$0: warning: no compiler for $dialect-$arch" >&2 ;;
 	esac
 	slc_filter=cp
 	;;
@@ -290,9 +295,10 @@ case $slc_os in
 		fi
             done
 	    if test -z "$found"; then
-		die "slrt.o not found for $slc_arch-$slc_os in $slc_libdir"
-            fi
-            slc_ldflags="$slc_ldflags $found"
+		echo "$0: warning: slrt.o not found for $slc_arch-$slc_os in $slc_libdir" >&2
+            else
+		slc_ldflags="$slc_ldflags $found"
+	    fi
         fi
 
 	if test "$slc_use_slos" != "no"; then
diff --git a/bin/sgr.in b/bin/sgr.in
--- a/bin/sgr.in
+++ b/bin/sgr.in
@@ -5,7 +5,11 @@ copyright="Copyright (C) 2009 the CSA group - The SL project."
 # All rights reserved.
 
 set -e
+python=${PYTHON:-@python@}
+slc_helper=${SLC:-@slc_helper@}
+sag_helper=${SAG:-@sag_helper@}
 slc_libdir=${SLC_LIBDIR:-@slc_libdir@}
+slc_datadir=${SLC_DATADIR:-@slc_datadir@}
 
 timestamp=$(echo '$Date$'|cut -d' ' -f2)
 version=1
@@ -23,6 +27,7 @@ Usage: $0 [OPTION] PROGRAM [ARGS]...
 Options:
   -r runner      use the specified runner (use when autodetect fails)
   -x             show configuration string embedded in program (if any)
+  -Ws,arg        pass "arg" as extra command-line parameter to the runner
   -h, --help     print this help, then exit
   -v, --version  print version number, then exit
 
@@ -55,10 +60,15 @@ EOF
   exit 0
 }
 
+die() {
+  printf '%s: %s\n' "$0" "$2" >&2
+  exit $1
+}
 
 # Command line analysis
 prev_arg=
 show_embedded=
+lowargs=
 for arg in "$@"; do
   # if the previous option needs an argument, assign it
   if test -n "$prev_arg"; then
@@ -72,8 +82,11 @@ for arg in "$@"; do
       -x)	show_embedded=1; shift;;
       -v|--version)	do_version;;
       -h|--help)	do_usage;;
+      -Ws*)   lowarg=$(echo "$arg"|cut -d',' -f2-|tr ',' ' ')
+	  lowargs="$lowargs $lowarg"
+	  shift;;
       --)  break;;
-      -*) echo "$0: unrecognized command-line argument: $arg (try -h)" >&2; exit 1;;
+      -*)  die 1 "unrecognized command-line argument: $arg (try -h)";;
       *)   break;;
   esac
 done
@@ -83,14 +96,12 @@ shift
 
 # does the program exist?
 if ! test -f "$program"; then
-  echo "$0: no such file or directory: $program" >&2
-  exit 127
+  die 127 "no such file or directory: $program"
 fi
 
 # is it executable?
 if ! test -x "$program"; then
-  echo "$0: permission denied: $program" >&2
-  exit 126
+  die 126 "permission denied: $program"
 fi
 
 if test -n "$show_embedded" -o -z "$runner"; then
@@ -108,18 +119,24 @@ if test -n "$show_embedded" -o -z "$runner"; then
   fi
 fi
 
+datatag=$(strings "$program"|grep '^sgr_datatag:.*:'|tail -n1|cut -d: -f2)
+if test "x$datatag" = "x"; then
+    die 1 "can't determine cce tag to recompile"
+fi
+
+
 if test -z "$runner"; then
   # Not specified, use tag if found
   if test -n "$tag"; then
      runner=$tag
   else
-     echo "$0: can't determine runner (try -r)" >&2
-     exit 1
+     die 1 "can't determine runner (try -r)"
   fi
 fi
 
 # check it
 runner_script=
+saveIFS=$IFS
 IFS=:
 for l in $slc_libdir; do
   if test -r "$l/r-$runner/run.sh"; then
@@ -128,9 +145,80 @@ for l in $slc_libdir; do
   fi
 done
 if test -z "$runner_script"; then
-    echo "$0: $runner: cannot find runner script" >&2
+    die 1 "$runner: cannot find runner script"
+fi
+IFS=$saveIFS
+
+cleanfiles=
+docleanup() {
+    for f in $cleanfiles; do
+	if test -z "$KEEP"; then
+	    rm -rf "$f" >/dev/null 2>&1
+	else
+	    echo "$0: $f: left over temporary" >&2
+	fi
+    done
+}
+
+trapcleanup() {
+    local sig
+    sig=$1
+    docleanup
+    trap - INT PIPE TERM QUIT ALRM
+    kill -$sig $$
+}
+errcleanup() {
+    docleanup
+    trap - ERR
     exit 1
+}
+
+trap 'trapcleanup INT' INT
+trap 'trapcleanup PIPE' PIPE
+trap 'trapcleanup TERM' TERM
+trap 'trapcleanup QUIT' QUIT
+trap 'trapcleanup ALRM' ALRM
+trap 'errcleanup' ERR
+
+# build temporary directory
+baseout=$(basename "$program")
+tmpdir=$(mktemp -d -t "$baseout".XXXXXXXX)
+cleanfiles=$tmpdir
+
+# check program parameters
+strings "$program" | (grep '^sgr_arg:'||true) >"$tmpdir"/args.spec
+if test -s "$tmpdir"/args.spec; then
+    $python "$sag_helper" "$@" <"$tmpdir"/args.spec >"$tmpdir"/data.c
+
+    found=
+    saveIFS=$IFS
+    IFS=:
+    for d in $slc_datadir; do
+	if test -r "$d/arggen.sl"; then
+	    found=$d/arggen.sl
+	    break
+	fi
+    done
+    IFS=$saveIFS
+    if test -z "$found"; then
+	die 1 "arggen.sl not found in $slc_datadir"
+    fi
+    mkdir "$tmpdir"/slc-rec
+    TMPDIR="$tmpdir"/slc-rec @BASH@ "$slc_helper" -b "$datatag" -o "$tmpdir"/gen.x -I"$tmpdir" "$found"
+    mkdir "$tmpdir"/sgr-rec
+    TMPDIR="$tmpdir"/sgr-rec @BASH@ "$0" "$tmpdir"/gen.x >"$tmpdir"/data 2>/dev/null
+else
+    touch "$tmpdir"/data
 fi
 
-exec @BASH@ "$runner_script" "$program" "$@"
+#set +e
+@BASH@ "$runner_script" "$program" "$tmpdir"/data $lowargs
+#set -e
+docleanup
+trap - ERR
+#trap - ERR INT PIPE TERM QUIT ALRM
+#if test $x -gt 128; then
+#    kill -$(expr $x - 128) $$
+#fi
+#exit $x
 
diff --git a/lib/r-mtalpha-sim/run.sh.in b/lib/r-mtalpha-sim/run.sh.in
--- a/lib/r-mtalpha-sim/run.sh.in
+++ b/lib/r-mtalpha-sim/run.sh.in
@@ -1,9 +1,21 @@
 #! /bin/sh
 # $Id$
 MGSIM_ALPHA=${MGSIM_ALPHA:-@MGSIM_ALPHA@}
+program=${1:?}
+datafile=${2:?}
+shift
+shift
+if ! test -x "$program"; then
+    echo "$0: $program: not an executable" >&2
+    exit 1
+fi
+if ! test -r "$datafile"; then
+    echo "$0: $datafile: file not found or not readable" >&2
+    exit 1
+fi
 
 if ! "$MGSIM_ALPHA" --help >/dev/null 2>&1; then
   echo "Can't find simulator? Please set env. var. MGSIM_ALPHA to simulator executable." >&2
   exit 1
 fi
-exec $MGSIM_ALPHA -R16 0 $SIMARGS -t "$@"
+exec $MGSIM_ALPHA $SIMARGS -t "$@" -L16 "$datafile" "$program"
