More bug fixes thanks to Andrei Matei.
* bin/cce.in: Use $slc_libdir to find the slrt and library, not
$slc_datadir.

* bin/slc.in: Give a source file's directory as extra -I to m4 to
allow m4_include's to work a bit more like CPP's #include "".

* configure.ac: Search for a suitable $(LN_S).	
* doc/Makefile.am: Use it. Fixes use of picture in document when
building in a separate directory.

* configure.ac: The Sparc utilities have architecture name
mtsparc-leon-linux, not mtsparc-linux-gnu.

* Makefile.am: Extract more rules outside of the maintainer mode,
as suggested by Andrei.

* tests.mk (TESTS_ENVIRONMENT): Run "slt" with $(SHELL), so that
extra shell arguments can be passed on the command line of "make
check".

diff --git a/bin/cce.in b/bin/cce.in
--- a/bin/cce.in
+++ b/bin/cce.in
@@ -279,12 +279,14 @@ case $slc_os in
         IFS=:
         for d in $slc_datadir; do
             slc_ppflags="$slc_ppflags -I$d/$slc_arch-$slc_os/include"
+        done
+        for d in $slc_libdir; do
             slc_ldflags="$slc_ldflags -L$d/$slc_arch-$slc_os"
         done
         slc_ldflags="$slc_ldflags -lslos"
 
         found=
-        for d in $slc_datadir; do
+        for d in $slc_libdir; do
   	    osdir=$d/$slc_arch-$slc_os
             if test -r "$osdir/slrt.o"; then
               found=$osdir/slrt.o
@@ -292,7 +294,7 @@ case $slc_os in
             fi
         done
 	if test -z "$found"; then
-           echo "$0: warning: slrt.o not found for $slc_arch-$slc_os in $slc_datadir" >&2
+           echo "$0: warning: slrt.o not found for $slc_arch-$slc_os in $slc_libdir" >&2
         fi
         slc_ldflags="$slc_ldflags $found"
          
