Make debugging easier.
* bin/slr.in: Rename option -x to -c. Use -x for new "tracing"
feature (print commands before running them). Add option -g to run
command with debugger. Improve documentation to reflect the
feature changes.

* lib/r-mtalpha-sim/run.sh.in,
* lib/r-mtsparc-sim/run.sh.in,
* lib/r-host/run.sh: Recognize VERBOSE, DEBUG and DEBUGGER. 

* bin/slt.in: Always put temporary file in a subdirectory of the
current directory, instead of the source directory. This makes
TEST_HERE obsolete. Give -x to `slr' for better logging.

* tests.mk (TESTS_ENVIRONMENT): Simplify accordingly. 

* bin/slr.in,
* bin/slc.in: Better use TMPDIR and mktemp to reduce the size of
temporary directory paths.

diff --git a/bin/slc.in b/bin/slc.in
--- a/bin/slc.in
+++ b/bin/slc.in
@@ -7,6 +7,7 @@ copyright="Copyright (C) 2009 The SL project.."
 set -e
 cce_helper=${CCE:-@cce_helper@}
 basename=$(basename "$0")
+TMPDIR=${TMPDIR:-/tmp}
 
 # Interface version number
 version=2
@@ -440,11 +441,16 @@ esac
 
 # Create temporary directory if necessary
 if test -n "$tmpdir"; then
-    if ! test -d "$tmpdir" -a -w "$tmpdir"; then
-	die "$tmpdir: cannot write to directory"
+    if test -e "$tmpdir"; then
+	if ! test -d "$tmpdir" -a -w "$tmpdir"; then
+           die "$tmpdir: cannot write to directory"
+        fi
+    else
+        mkdir -p "$tmpdir"
+	tempdirs=$tmpdir
     fi
 else
-    tmpdir=$(mktemp -d -t slc.XXXXXXXX)
+    tmpdir=$(mktemp -d $TMPDIR/slc.XXXXXXXX)
     tempdirs=$tmpdir
 fi
 
diff --git a/lib/r-mtalpha-sim/run.sh.in b/lib/r-mtalpha-sim/run.sh.in
--- a/lib/r-mtalpha-sim/run.sh.in
+++ b/lib/r-mtalpha-sim/run.sh.in
@@ -3,6 +3,7 @@
 MGSIM_ALPHA=${MGSIM_ALPHA:-@MGSIM_ALPHA@}
 program=${1:?}
 datafile=${2:?}
+DEBUGGER=${DEBUGGER:-gdb --args}
 shift
 shift
 if ! test -x "$program"; then
@@ -15,7 +16,16 @@ if ! test -r "$datafile"; then
 fi
 
 if ! "$MGSIM_ALPHA" --help >/dev/null 2>&1; then
-  echo "Can't find simulator? Please set env. var. MGSIM_ALPHA to simulator executable." >&2
+  echo "$0: cannot find simulator (MGSIM_ALPHA=$MGSIM_ALPHA)." >&2
   exit 1
 fi
-exec $MGSIM_ALPHA $SIMARGS -t "$@" -L16 "$datafile" "$program"
+
+do_debug=
+if test -n "$DEBUG"; then
+   SIMARGS="$SIMARGS -i"
+   do_debug=$DEBUGGER
+fi
+if test -n "$VERBOSE"; then
+   echo "$0: running: $do_debug $MGSIM_ALPHA $SIMARGS -t $* -L16 $datafile $program" >&2
+fi  
+exec $do_debug $MGSIM_ALPHA $SIMARGS -t "$@" -L16 "$datafile" "$program"
diff --git a/lib/r-mtsparc-sim/run.sh.in b/lib/r-mtsparc-sim/run.sh.in
--- a/lib/r-mtsparc-sim/run.sh.in
+++ b/lib/r-mtsparc-sim/run.sh.in
@@ -1,9 +1,31 @@
 #! /bin/sh
 # $Id$
 MGSIM_SPARC=${MGSIM_SPARC:-@MGSIM_SPARC@}
+program=${1:?}
+datafile=${2:?}
+DEBUGGER=${DEBUGGER:-gdb --args}
+shift
+shift
+if ! test -x "$program"; then
+    echo "$0: $program: not an executable" >&2
+    exit 1
+fi
+if ! test -r "$datafile"; then
+    echo "$0: $datafile: file not found or not readable" >&2
+    exit 1
+fi
 
 if ! "$MGSIM_SPARC" --help >/dev/null 2>&1; then
-  echo "Can't find simulator? Please set env. var. MGSIM_SPARC to simulator executable." >&2
+  echo "$0: cannot find simulator (MGSIM_SPARC=$MGSIM_SPARC)." >&2
   exit 1
 fi
-exec $MGSIM_SPARC $SIMARGS -t "$@"
+
+do_debug=
+if test -n "$DEBUG"; then
+   SIMARGS="$SIMARGS -i"
+   do_debug=$DEBUGGER
+fi
+if test -n "$VERBOSE"; then
+   echo "$0: running: $do_debug $MGSIM_SPARC $SIMARGS -t $* -L16 $datafile $program" >&2
+fi  
+exec $do_debug $MGSIM_SPARC $SIMARGS -t "$@" -L16 "$datafile" "$program"
