Improve interface of SL runner.
* bin/slr.in: Reinstate use of -x to select runner. Use -t for
trace instead of -x.
* bin/slt.in: Update accordingly.

* bin/slr.in: Support new options -r and -w to load/save the data
file from a file. This allows to cache an input data file between
runs. 

* bin/slr.in: Support new option -n as shorthand for the number of
cores.
* lib/r-mtalpha-sim/run.sh.in,
* lib/r-mtsparc-sim/run.sh.in: Update accordingly.

* bin/slc.in,
* bin/slr.in: Update documentation for TMPDIR.

diff --git a/bin/slr.in b/bin/slr.in
--- a/bin/slr.in
+++ b/bin/slr.in
@@ -38,31 +38,42 @@ This uses the SL input mechanism described in CSA note [sl3].
 
 Usage: $0 [OPTION] PROGRAM [ARGS]...
 
-Options:
+Program input options:
+  -l                   List variables required as input by the program.
+
   -dVAR                Define the program input VAR as an empty array.
 
   -dVAR=..., VAR=...   Define the program input VAR as specified (see 
                        CSA note [sl3] for details).
 
-  -l                   List variables required as input by the program.
+  -w FILE              Save the binary input data generated by the -d flags
+                       to the specified FILE.
+
+  -r FILE              Load the binary input data saved previously with -w from
+                       FILE. This overrides any -d option.
+
+Execution selection:
+  -n N                 Try to run with only N SVP cores.
 
   -c                   Show configuration string embedded in program, if any.
 
-  -r runner            Use the specified runner (use when autodetect fails).
+  -x RUNNER            Use the specified RUNNER (use when autodetect fails).
 
   -Ws,arg              Pass "arg" as extra command line parameter to the 
                        simulator, when the simulator is used.
 
-  -x                   Trace: print commands before running them.
+Debugging options:
+  -t                   Trace: print commands before running them.
 
   -g                   Debug: try to run debugger around program. Implies -x.
 
+Other options:
   -h, --help           Print this help, then exit.
 
   -v, --version        Print version number, then exit.
 
 Environment variables:
-  VERBOSE              If set and not empty, implies option -x.
+  VERBOSE              If set and not empty, implies option -t.
 
   DEBUG                If set and not empty, implies option -g.
 
@@ -71,6 +82,9 @@ Environment variables:
 
   SIMARGS              Combines with the occurrences of option -Ws on
                        the command line when running the simulator.
+
+  TMPDIR             If set and not empty, overrides /tmp as the
+                     base directory for temporary files.
 
 Examples:
 
@@ -83,12 +97,11 @@ Examples:
   Runs fibo.x, possibly using the MT simulator, and set program input
   variable N to an array of 1 element with value "15".
 
-  \$ slr fibo.x -dN=10 -Ws,-o -Ws,NumProcessors=7
+  \$ slr fibo.x N=10 -n 7
 
   Runs fibo.x, possibly using the MT simulator, and set program input
-  variable N to an array of 1 element with value "10". If the
-  simulator is used, add "-o NumProcessors=7" to the simulator command
-  line.
+  variable N to an array of 1 element with value "10". Try to run
+  with 7 SVP cores.
 
 Report bugs and patches to $bugreports.
 EOF
@@ -121,6 +134,9 @@ show_embedded=
 vars=
 program=
 query=
+rdatafile=
+wdatafile=
+NCORES=${NCORES:-}
 SIMARGS=${SIMARGS:-}
 VERBOSE=${VERBOSE:-}
 DEBUG=${DEBUG:-}
@@ -133,18 +149,21 @@ for arg in "$@"; do
      continue
   fi
   case $arg in
-      -r)	prev_arg=runner; shift;;
+      -x)	prev_arg=runner; shift;;
       -c)	show_embedded=1; shift;;
-      -x)       VERBOSE=1; shift;;
+      -t)       VERBOSE=1; shift;;
       -g)	VERBOSE=1; DEBUG=1; shift;;
       -v|--version)	do_version;;
       -h|--help)	do_usage;;
-      -l|--list)  query=1; shift;;
+      -l)  query=1; shift;;
+      -n)  prev_arg=NCORES; shift;;
       -Ws*)   lowarg=$(echo "$arg"|cut -d',' -f2-|tr ',' ' ')
 	  SIMARGS="$SIMARGS $lowarg"
 	  shift;;
       -d*=*) var=$(printf "%s" "$arg"|cut -c3-); vars="$vars $var"; shift;;
       -d*) var=$(printf "%s" "$arg"|cut -c3-); vars="$vars $var="; shift;;
+      -r)  prev_arg=rdatafile; shift;;
+      -w)  prev_arg=wdatafile; shift;;
       --)  break;;
       -*)  die 1 "unrecognized command-line argument: $arg (try -h)";;
       *=*) vars="$vars $arg"; shift ;;
@@ -234,6 +253,14 @@ errcleanup() {
     exit 1
 }
 
+if test -n "$rdatafile"; then
+  if ! test -r "$rdatafile"; then die "$rdatafile: cannot read file"; fi
+  datafile=$rdatafile
+  dodata=
+else
+  dodata=1
+fi
+
 trap 'trapcleanup INT' INT
 trap 'trapcleanup PIPE' PIPE
 trap 'trapcleanup TERM' TERM
@@ -241,57 +268,64 @@ trap 'trapcleanup QUIT' QUIT
 trap 'trapcleanup ALRM' ALRM
 trap 'errcleanup' ERR
 
-# build temporary directory
-baseout=$(basename "$program")
-tmpdir=$(mktemp -d $TMPDIR/"$baseout".XXXXXXXX)
-cleanfiles=$tmpdir
+if test -n "$dodata"; then
+    # build temporary directory
+    baseout=$(basename "$program")
+    tmpdir=$(mktemp -d $TMPDIR/"$baseout".XXXXXXXX)
+    cleanfiles=$tmpdir
 
-# check program parameters
-strings "$program" | (grep '^slr_arg:'||true) >"$tmpdir"/args.spec
-if test -n "$query"; then
-  $python "$sag_helper" list <"$tmpdir"/args.spec
-  exit 0
-fi
-
-if test -s "$tmpdir"/args.spec; then
-    if test -n "$VERBOSE"; then
-      echo "$0: running: $python $sag_helper $vars <$tmpdir/args.spec >$tmpdir/data.c" >&2
+    if test -n "$wdatafile"; then
+	datafile=$wdatafile
+    else    
+	datafile="$tmpdir"/data
     fi
-    $python "$sag_helper" $vars <"$tmpdir"/args.spec >"$tmpdir"/data.c
-
-    found=
-    saveIFS=$IFS
-    IFS=:
-    for d in $slc_datadir; do
-	if test -r "$d/arggen.sl"; then
-	    found=$d/arggen.sl
-	    break
+    
+    # check program parameters
+    strings "$program" | (grep '^slr_arg:'||true) >"$tmpdir"/args.spec
+    if test -n "$query"; then
+	$python "$sag_helper" list <"$tmpdir"/args.spec
+	exit 0
+    fi
+      
+    if test -s "$tmpdir"/args.spec; then
+	if test -n "$VERBOSE"; then
+	    echo "$0: running: $python $sag_helper $vars <$tmpdir/args.spec >$tmpdir/data.c" >&2
 	fi
-    done
-    IFS=$saveIFS
-    if test -z "$found"; then
-	die 1 "arggen.sl not found in $slc_datadir"
+	$python "$sag_helper" $vars <"$tmpdir"/args.spec >"$tmpdir"/data.c
+	
+	found=
+	saveIFS=$IFS
+	IFS=:
+	for d in $slc_datadir; do
+	    if test -r "$d/arggen.sl"; then
+		found=$d/arggen.sl
+		break
+	    fi
+	done
+	IFS=$saveIFS
+	if test -z "$found"; then
+	    die 1 "arggen.sl not found in $slc_datadir"
+	fi
+	mkdir "$tmpdir"/slc-rec
+	if test -n "$VERBOSE"; then
+	    echo "$0: running: TMPDIR=$tmpdir/slc-rec @BASH@ $slc_helper -b $datatag -o $tmpdir/gen.x -I$tmpdir $found" >&2
+	fi
+	TMPDIR="$tmpdir"/slc-rec @BASH@ "$slc_helper" -b "$datatag" -o "$tmpdir"/gen.x -I"$tmpdir" "$found"
+	mkdir "$tmpdir"/slr-rec
+	if test -n "$VERBOSE"; then
+	    echo "$0: running: TMPDIR=$tmpdir/slr-rec @BASH@ $0 $tmpdir/gen.x >$datafile 2>$tmpdir/gen.log" >&2
+	fi
+	TMPDIR="$tmpdir"/slr-rec @BASH@ "$0" "$tmpdir"/gen.x >"$datafile" 2>"$tmpdir"/gen.log
+    else
+	touch "$tmpdir"/data
     fi
-    mkdir "$tmpdir"/slc-rec
-    if test -n "$VERBOSE"; then
-       echo "$0: running: TMPDIR=$tmpdir/slc-rec @BASH@ $slc_helper -b $datatag -o $tmpdir/gen.x -I$tmpdir $found" >&2
-    fi
-    TMPDIR="$tmpdir"/slc-rec @BASH@ "$slc_helper" -b "$datatag" -o "$tmpdir"/gen.x -I"$tmpdir" "$found"
-    mkdir "$tmpdir"/slr-rec
-    if test -n "$VERBOSE"; then
-       echo "$0: running: TMPDIR=$tmpdir/slr-rec @BASH@ $0 $tmpdir/gen.x >$tmpdir/data 2>$tmpdir/gen.log" >&2
-    fi
-    TMPDIR="$tmpdir"/slr-rec @BASH@ "$0" "$tmpdir"/gen.x >"$tmpdir"/data 2>"$tmpdir"/gen.log
-else
-    touch "$tmpdir"/data
 fi
-
 #set +e
-export SIMARGS VERBOSE DEBUG
+export SIMARGS VERBOSE DEBUG NCORES
 if test -n "$VERBOSE"; then
-   echo "$0: running: @BASH@ $runner_script $program $tmp/data" >&2
+    echo "$0: running: @BASH@ $runner_script $program $datafile" >&2
 fi
-@BASH@ "$runner_script" "$program" "$tmpdir"/data 
+@BASH@ "$runner_script" "$program" "$datafile"
 #set -e
 docleanup
 trap - ERR
@@ -300,4 +334,5 @@ trap - ERR
 #    kill -$(expr $x - 128) $$
 #fi
 #exit $x
-
+    
+    
