Implement Fibre input.
* include/fibre.slh: Add.

* bin/sag: Encapsulate existing code as class SlrVarGenerator. Add
new class FibreGenerator.	
* bin/slr.in: Use it. Rename -w and -r to -wd and -rd. Implement
-wf, -rf, -wo. Document KEEP.

* lib/arggen.sl: Include either "data.c" or "fdata.c".

* lib/r-mtsparc-sim/run.sh.in,
* lib/r-mtalpha-sim/run.sh.in: Give Fibre data via -L17.	
* lib/mtalpha-sim/slrt.s: Save $l17 to __fibre_data. Fix loading
of pointer addresses via GP (use 'ldq ... !literal' instead of
'lda').

* lib/host-host-seqc/load.c: Give target pointer to set as
parameter to support loading multiple files.
* lib/host-host-seqc/slrt.c,
* lib/host-host-ptl/slrt.c: Use it to load both SLR vars data and
Fibre data.

* lib/r-host/run.sh: Give both data files on the command line.

* doc/NEWS.txt: Mention the new feature.

diff --git a/bin/slr.in b/bin/slr.in
--- a/bin/slr.in
+++ b/bin/slr.in
@@ -46,11 +46,23 @@ Program input options:
   -dVAR=..., VAR=...   Define the program input VAR as specified (see 
                        CSA note [sl3] for details).
 
-  -w FILE              Save the binary input data generated by the -d flags
-                       to the specified FILE.
+  -wd FILE             Save the binary input data generated by the -d flags
+                       to the specified FILE. 
 
-  -r FILE              Load the binary input data saved previously with -w from
+  -rd FILE             Load the binary input data saved previously with -wd from
                        FILE. This overrides any -d option.
+
+  -f FILE              Load Fibre I/O data from FILE.
+
+  -wf FILE             Save the binary input data generated by -f to the
+                       specified FILE.
+
+  -rf FILE             Load the binary input data saved previously with -wx from
+                       FILE. This overrides option -f.  
+
+  -wo                  Stop after reading the input data; do not run the
+                       program (useful with -wd and -wf to cache the input
+                       before many runs).
 
 Execution selection:
   -n N                 Try to run with only N SVP cores.
@@ -83,8 +95,11 @@ Environment variables:
   SIMARGS              Combines with the occurrences of option -Ws on
                        the command line when running the simulator.
 
-  TMPDIR             If set and not empty, overrides /tmp as the
-                     base directory for temporary files.
+  TMPDIR               If set and not empty, overrides /tmp as the
+                       base directory for temporary files.
+
+  KEEP                 If set and not empty, do not delete temporary
+                       files after completion.
 
 Examples:
 
@@ -135,7 +150,11 @@ vars=
 program=
 query=
 rdatafile=
+rfdatafile=
 wdatafile=
+wfdatafile=
+preponly=
+fibre_in=
 NCORES=${NCORES:-}
 SIMARGS=${SIMARGS:-}
 VERBOSE=${VERBOSE:-}
@@ -162,8 +181,12 @@ for arg in "$@"; do
 	  shift;;
       -d*=*) var=$(printf "%s" "$arg"|cut -c3-); vars="$vars $var"; shift;;
       -d*) var=$(printf "%s" "$arg"|cut -c3-); vars="$vars $var="; shift;;
-      -r)  prev_arg=rdatafile; shift;;
-      -w)  prev_arg=wdatafile; shift;;
+      -f)   prev_arg=fibre_in; shift;;
+      -rd)  prev_arg=rdatafile; shift;;
+      -wd)  prev_arg=wdatafile; shift;;
+      -rf)  prev_arg=rfdatafile; shift;;
+      -wf)  prev_arg=wfdatafile; shift;;
+      -wo)  preponly=1; shift;;
       --)  break;;
       -*)  die 1 "unrecognized command-line argument: $arg (try -h)";;
       *=*) vars="$vars $arg"; shift ;;
@@ -227,7 +250,18 @@ done
 if test -z "$runner_script"; then
     die 1 "$runner: cannot find runner script"
 fi
+
+arggen=
+for d in $slc_datadir; do
+    if test -r "$d/arggen.sl"; then
+	arggen=$d/arggen.sl
+	break
+    fi
+done
 IFS=$saveIFS
+if test -z "$arggen"; then
+    die 1 "arggen.sl not found in $slc_datadir"
+fi
 
 cleanfiles=
 docleanup() {
@@ -256,12 +290,23 @@ errcleanup() {
 if test -n "$rdatafile"; then
   if ! test -r "$rdatafile"; then die "$rdatafile: cannot read file"; fi
   if test -n "$vars"; then 
-    echo "$0: warning: '-r $rdatafile' overrides '$vars'" >&2
+    echo "$0: warning: '-rd $rdatafile' overrides '$vars'" >&2
   fi
   datafile=$rdatafile
   dodata=
 else
   dodata=1
+fi
+
+if test -n "$rfdatafile"; then
+  if ! test -r "$rfdatafile"; then die "$rfdatafile: cannot read file"; fi
+  if test -n "$vars"; then 
+    echo "$0: warning: '-rf $rfdatafile' overrides '-f $fibre_in'" >&2
+  fi
+  fdatafile=$rfdatafile
+  dofdata=
+else
+  dofdata=1
 fi
 
 trap 'trapcleanup INT' INT
@@ -271,12 +316,14 @@ trap 'trapcleanup QUIT' QUIT
 trap 'trapcleanup ALRM' ALRM
 trap 'errcleanup' ERR
 
-if test -n "$dodata"; then
+if test -n "$dodata" -o -n "$dofdata"; then
     # build temporary directory
     baseout=$(basename "$program")
     tmpdir=$(mktemp -d $TMPDIR/"$baseout".XXXXXXXX)
     cleanfiles=$tmpdir
+fi
 
+if test -n "$dodata"; then
     if test -n "$wdatafile"; then
 	datafile=$wdatafile
     else    
@@ -292,50 +339,77 @@ if test -n "$dodata"; then
       
     if test -s "$tmpdir"/args.spec; then
 	if test -n "$VERBOSE"; then
-	    echo "$0: running: $python $sag_helper $vars <$tmpdir/args.spec >$tmpdir/data.c" >&2
+	    echo "$0: running: $python $sag_helper d $vars <$tmpdir/args.spec >$tmpdir/data.c" >&2
 	fi
-	$python "$sag_helper" $vars <"$tmpdir"/args.spec >"$tmpdir"/data.c
+	$python "$sag_helper" d $vars <"$tmpdir"/args.spec >"$tmpdir"/data.c
 	
-	found=
-	saveIFS=$IFS
-	IFS=:
-	for d in $slc_datadir; do
-	    if test -r "$d/arggen.sl"; then
-		found=$d/arggen.sl
-		break
-	    fi
-	done
-	IFS=$saveIFS
-	if test -z "$found"; then
-	    die 1 "arggen.sl not found in $slc_datadir"
-	fi
 	mkdir "$tmpdir"/slc-rec
 	if test -n "$VERBOSE"; then
-	    echo "$0: running: TMPDIR=$tmpdir/slc-rec @BASH@ $slc_helper -b $datatag -o $tmpdir/gen.x -I$tmpdir $found" >&2
+	    echo "$0: running: TMPDIR=$tmpdir/slc-rec @BASH@ $slc_helper -b $datatag -o $tmpdir/gen.x -I$tmpdir $arggen" >&2
 	fi
-	TMPDIR="$tmpdir"/slc-rec @BASH@ "$slc_helper" -b "$datatag" -o "$tmpdir"/gen.x -I"$tmpdir" "$found"
+	TMPDIR="$tmpdir"/slc-rec @BASH@ "$slc_helper" -b "$datatag" -o "$tmpdir"/gen.x -I"$tmpdir" "$arggen"
 	mkdir "$tmpdir"/slr-rec
 	if test -n "$VERBOSE"; then
 	    echo "$0: running: TMPDIR=$tmpdir/slr-rec @BASH@ $0 $tmpdir/gen.x >$datafile" >&2
 	fi
-	TMPDIR="$tmpdir"/slr-rec @BASH@ "$0" "$tmpdir"/gen.x -Ws,-q >"$datafile"
+	TMPDIR="$tmpdir"/slr-rec @BASH@ "$0" "$tmpdir"/gen.x -Ws,-q -n 1 >"$datafile"
     else
         true >"$datafile"
     fi
 fi
-#set +e
+
+if test -n "$dofdata"; then
+    if test -n "$wfdatafile"; then
+	fdatafile=$wfdatafile
+    else    
+	fdatafile="$tmpdir"/fdata
+    fi
+    
+    if test -n "$fibre_in"; then
+	if ! test -r "$fibre_in"; then die "$fibre_in: cannot read file"; fi
+
+        # check program parameters
+	if test -n "$VERBOSE"; then
+	    echo "$0: running: [sed] <$fibre_in |$python $sag_helper f >$tmpdir/fdata.c" >&2
+	fi
+	
+	sed -e 's/\#.*//g;' <"$fibre_in" | \
+	    (tr '\n' ' ';echo " None") | \
+	    sed -e 's/^ *//g;
+s/\[[0-9 ,]*: */\[/g;
+s/ *\]/\]/g;
+s/  */,/g;
+s/d0//g;
+s/,$//g' | $python "$sag_helper" f >"$tmpdir"/fdata.c
+	
+	mkdir "$tmpdir"/slc-rec
+	if test -n "$VERBOSE"; then
+	    echo "$0: running: TMPDIR=$tmpdir/slc-rec @BASH@ $slc_helper -b $datatag -o $tmpdir/gen.x -I$tmpdir -DFIBRE_DATA=1 $arggen" >&2
+	fi
+	TMPDIR="$tmpdir"/slc-rec @BASH@ \
+	    "$slc_helper" -b "$datatag" -o "$tmpdir"/gen.x -I"$tmpdir" -DFIBRE_DATA=1 "$arggen"
+	mkdir "$tmpdir"/slr-rec
+	if test -n "$VERBOSE"; then
+	    echo "$0: running: TMPDIR=$tmpdir/slr-rec @BASH@ $0 $tmpdir/gen.x >$fdatafile" >&2
+	fi
+	TMPDIR="$tmpdir"/slr-rec @BASH@ "$0" "$tmpdir"/gen.x -Ws,-q -n 1 >"$fdatafile"
+    else
+        true >"$fdatafile"
+    fi
+fi
+
+if test -n "$preponly"; then docleanup; exit 0; fi
+
 export SIMARGS VERBOSE DEBUG NCORES
 if test -n "$VERBOSE"; then
-    echo "$0: running: @BASH@ $runner_script $program $datafile" >&2
+    echo "$0: running: @BASH@ $runner_script $program $datafile $fdatafile" >&2
 fi
-@BASH@ "$runner_script" "$program" "$datafile"
-#set -e
+@BASH@ "$runner_script" "$program" "$datafile" "$fdatafile"
+
 docleanup
+
 trap - ERR
-#trap - ERR INT PIPE TERM QUIT ALRM
-#if test $x -gt 128; then
-#    kill -$(expr $x - 128) $$
-#fi
-#exit $x
-    
-    
+
+# Local variables:
+# mode: shell-script
+# End:
diff --git a/lib/r-mtsparc-sim/run.sh.in b/lib/r-mtsparc-sim/run.sh.in
--- a/lib/r-mtsparc-sim/run.sh.in
+++ b/lib/r-mtsparc-sim/run.sh.in
@@ -3,7 +3,9 @@
 MGSIM_SPARC=${MGSIM_SPARC:-@MGSIM_SPARC@}
 program=${1:?}
 datafile=${2:?}
+fdatafile=${3:?}
 DEBUGGER=${DEBUGGER:-gdb --args}
+shift
 shift
 shift
 if ! test -x "$program"; then
@@ -12,6 +14,11 @@ if ! test -x "$program"; then
 fi
 if ! test -r "$datafile"; then
     echo "$0: $datafile: file not found or not readable" >&2
+    exit 1
+fi
+
+if ! test -r "$fdatafile"; then
+    echo "$0: $fdatafile: file not found or not readable" >&2
     exit 1
 fi
 
@@ -30,6 +37,6 @@ if test -n "$DEBUG"; then
    do_debug=$DEBUGGER
 fi
 if test -n "$VERBOSE"; then
-   echo "$0: running: $do_debug $MGSIM_SPARC $SIMARGS -t $* -L16 $datafile $program" >&2
+   echo "$0: running: $do_debug $MGSIM_SPARC $SIMARGS -t $* -L16 $datafile -L17 $fdatafile $program" >&2
 fi  
-exec $do_debug $MGSIM_SPARC $SIMARGS -t "$@" -L16 "$datafile" "$program"
+exec $do_debug $MGSIM_SPARC $SIMARGS -t "$@" -L16 "$datafile" -L17 "$fdatafile" "$program"
