Improvements to test script.
* bin/slt: Remove test output when test is successful and KEEP is
not set. Factorize output of test results. Simplify display offset
computations. Improve documentation. Use different exit codes for
different exit situations. Propose license. Allow to use a local
directory to help "make distcheck" build from a directory
different from source.

* doc/Makefile.am: Build man page for 'slt'. Fix locations of
dependencies of language spec to be nice with "make distcheck".

diff --git a/bin/slt b/bin/slt
--- a/bin/slt
+++ b/bin/slt
@@ -1,14 +1,28 @@
 #! /bin/sh
 # $Id$
-
-# Tester script. Run with --help for details.
-
+#
+copyright="Copyright (C) 2009 the CSA group - The SL project."
+#
+# This program is free software: you can redistribute it and/or modify 
+# it under the terms of the GNU General Public License as published by   
+# the Free Software Foundation; either version 2, or (at your option)    
+# any later version.  
+#   
+# This program is distributed in the hope that it will be useful,   
+# but WITHOUT ANY WARRANTY; without even the implied warranty of    
+# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the     
+# GNU General Public License for more details.    
+#   
+# You should have received a copy of the GNU General Public License 
+# along with this program; if not, write to the Free Software 
+# Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA     
+# 02110-1301, USA.    
 set -e
-version=2
-rev='$Rev$'
-rev=$(echo "$rev"|cut -d' ' -f2)
 basename=$(basename "$0")
 root=$(cd $(dirname "$0"); pwd)
+
+# Interface version number
+version=2
 
 slc=${SLC:-$root/slc}
 runner=${SGR:-$root/sgr}
@@ -16,17 +30,40 @@ timeout=$root/timeout
 
 die() {
   echo "$0:" $@ >&2
-  exit 1
+  exit 2
 }
 
 usage() {
  cat <<EOF
-Usage: $basename [SOURCE] [IMPLEMENTATION]...
+SL Unit test and portability checker.
 
-Test the program SOURCE against the IMPLEMENTATIONs.
+\`$basename' is a generic tester script for SL programs. It tries to
+compile and execute the program given as input on multiple SVP
+implementations, comparing results.
+
+A test is considered to succeed when the following conditions are met:
+
+- the program compiles and links successfully on all specified SVP
+implementations, or it fails to compile on all implementations and
+it is marked as not compilable (see below);
+
+- the program runs successfully on all specified SVP implementations,
+or the program fails to run on all implementations and it is marked
+as not runnable (see below);
+
+- on all runs but the first, the console output of the program is
+identical to the output on the first run.
+
+Usage: $0 [SOURCE] [IMPLEMENTATION]...
+
+Options:
+
+  -h, --help    Print this help.
+  -v, --version Print a version number.
+
 
 Multiple implementations can be specified, and each multiple
-times. Implementations are filtered through the 'cce' utility.
+times. Implementations names are filtered through the \`cce' utility.
 
 Example implementation aliases:
 
@@ -40,7 +77,7 @@ Example implementation aliases:
 
   utcx          "desired muTC" (transform/preprocess only)
 
-If no IMPLEMENTATION is specified, or is set to "all", then the
+If no implementation is specified, or is set to "all", then the
 implementations list above are tested, in that order.
 
 The program performs the tests and display results as they become
@@ -50,62 +87,70 @@ SOURCE     XXYZ XXYZ XXYZ ...
 
 The first column contains the name of the SOURCE specified on the
 command line. Each subsequent column contains a string of tests
-results for the corresponding IMPLEMENTATION on the command line.
+results for the corresponding implementation specifier on the command
+line.
 
 Each string of test results has 3 positions:
 
-- compilation results; one of:
+1. compilation results; one of:
 
    L   An executable was produced successfully.
+
   8    A timeout occurred during compilation.
+
   !    A signal occurred during compilation.
+
   ?    Compilation succeeded, but a failure was expected.
  
   XT   Translation failed.
+
   XP   Preprocessing failed.
+
   XC   Compilation failed.
+
   XF   Post-compilation failed.
+
   XA   Assembly failed.
+
   XL   Linking failed.
 
   /T   Translation failed, as expected.
+
   /P   Preprocessing failed, as expected.
+
   /C   Compilation failed, as expected.
+
   /F   Post-compilation failed, as expected.
+
   /A   Assembly failed, as expected.
+
   /L   Linking failed, as expected.
 
-- execution results; one of:
+2) execution results; one of:
 
   R    Execution succeded without errors.
+
   8    A timeout occurred.
+
   !    A signal occurred.
+
   ?    Execution succeeded, but a failure was expected.
+
   o    A timeout occurred, as expected.
+
   .    A signal occurred, as expected.
 
-- check of reference output; one of:
+  -    The program was not run.
 
-  =   
-  D   compare results (check output against reference, see below)
+3) check of reference output; one of:
 
-For each position the following results can be produced:
+  =   The output will be reused as reference.
 
-  T,P,C,F,A,L,R (green) The phase succeeded (success)
-  = (green)             The output is used as reference. (success)
-  D (green)             The output is identical to the reference. (success)
+  D   The output is identical to the reference.
 
-  / (yellow)            An expected error occurred (success)
-  o (yellow)            An expected timeout occurred (success)
-  . (yellow)            An expected signal occurred (success)
-  | (yellow)            Test not defined. (newcore-sim only)
+  X   The output is different from the reference.
 
-  X (red)               An error occured (failure)
-  8 (red)               A timeout occurred (failure)
-  ! (red)               A signal occurred (failure)
-  ? (red)               Expected failure, test succeeded (failure)
-
-  - (white)             The phase was skipped.
+  -   The output was not checked.
 
 To indicate expected failures, the source code can be annotated as
 follows:
@@ -125,25 +170,72 @@ implementations are checked against the results of the first run.
 During testing a number of intermediate files are generated. If the
 SOURCE file is named test.sl, the following files are generated:
 
-  IMPL/test.log        Test log
-  IMPL/test.{c,cc,utc} Source code after transformation
-  IMPL/test.{i,ii,ui}  Source code after preprocessing
-  IMPL/test.s0         Raw assembly output
-  IMPL/test.s          Assembly output
-  IMPL/test.o          Object file
-  IMPL/test.x          Executable
-  IMPL/test.out        Output during execution
+  IMPL/test.log         Test log
+
+  IMPL/test.{c,cc,utc}  Source code after transformation
+
+  IMPL/test.{i,ii,ui}   Source code after preprocessing
+
+  IMPL/test.s0          Raw assembly output
+
+  IMPL/test.s           Assembly output
+
+  IMPL/test.o           Object file
+
+  IMPL/test.x           Executable
+
+  IMPL/test.out         Output during execution
 
 If a test is successful the corresponding files are erased after the
 test completes, unless the environment variable KEEP is set and
 non-empty.
 
-Report bugs and suggestions to the CSA Trac issue tracker,
-or to <r.c.poss@uva.nl>.
+Environment variables:
+  SLC            Location of the SL compiler. Default is 
+                 "$root/slc".
+
+  SGR            Location of the SVP generic runner. Default is 
+                 "$root/sgr"
+
+  KEEP           If set, do not erase intermediary files when a test
+                 succeeds. Default is not set.
+
+  TEST_HERE      If set, use a subdirectory in the current directory
+                 for each implementation instead of a subdirectory
+                 in the program's source directory.
+
+Diagnostics:
+  0              The test succeeded.
+
+  1              The test failed.
+
+  2              Invalid test parameters.
+
+Report bugs and suggestions to the CSA issue tracker.
 EOF
    exit 0 
 }
 
+
+if test "$1" = "--help" -o "$1" = "-h"; then
+  usage
+  exit 0
+elif test "$1" = "--version" -o "$1" = "-v"; then
+  rev='$Rev$'
+  rev=$(echo "$rev"|cut -d' ' -f2)
+  cat <<EOF
+$basename $version.$rev
+
+$copyright
+This is free software; see the source for copying conditions.  There is NO
+warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
+
+Written by Raphael 'kena' Poss.
+EOF
+  exit 0
+fi
+
+# Sanity check: verify that dependencies are there.
 test_exec() {
   if ! test -x "$1"; then
      die "$1: not found or not executable"
@@ -153,22 +245,8 @@ test_exec "$slc"
 test_exec "$runner"
 test_exec "$timeout"
 
-if test "$1" = "--help" -o "$1" = "-h"; then
-  usage
-  exit 0
-elif test "$1" = "--version" -o "$1" = "-v"; then
-  cat <<EOF
-$basename $version.$rev
-
-Copyright (C) 2008 the CSA group - The SL project
-
-Written by Raphael "kena" Poss.
-EOF
-  exit 0
-fi
-
 # Compute base name and directory of test source.
-testdir=${TESTDIR:-$(dirname "$1")}
+testdir=$(dirname "$1")
 testsrc=$1
 
 case $1 in
@@ -179,7 +257,7 @@ case $1 in
 Usage: $basename [SOURCE] [IMPLEMENTATION]...
    or: $basename -h
 EOF
-   exit 1
+   exit 2
 esac
 
 shift
@@ -197,13 +275,8 @@ case $1 in
     ;;
 esac
 
-if test ! -d $testdir -o ! -w $testdir; then
-   echo "$testdir: directory does not exist or read-only" >&2
-   exit 1
-fi
 if test ! -r $testsrc; then
-   echo "$testsrc: cannot read file" >&2
-   exit 1
+   die "$testsrc: cannot read file" 
 fi
 
 check_status() {
@@ -221,6 +294,14 @@ check_status() {
     if test $status = invcmd || test $status = signal -a "$signal" = 2; then exit $1; fi
 }
 
+place_chars() {
+  local offset color chars str
+  offset=$1
+  color=$2
+  chars=$3
+  str=$(printf '\r\033[%sC\033[%sm%s\e[0m' $offset $color "$chars")
+  printf "%s" "$str"
+}
 
 report_compile() {
   local code offset color char str outlog
@@ -255,8 +336,7 @@ report_compile() {
   if test $fail = 1; then
     dorun=0
   fi
-  str=$(printf '\r\033[%sC\033[%sm%s\e[0m' $offset $color "$char")
-  printf "%s" "$str"
+  place_chars $offset $color "$char"
 }
 
 report_run() {
@@ -276,8 +356,7 @@ report_run() {
     error)   dodiff=0;
              if grep -q "XFAIL:.*R" "$testsrc"; then color=33; char="/"; else color=31; char="X"; fail=1; fi;;
   esac
-  str=$(printf '\r\033[%sC\033[%sm%s\e[0m' $offset $color "$char")
-  printf "%s" "$str"
+  place_chars $offset $color "$char"
 }
 
 do_compile() {
@@ -301,8 +380,7 @@ do_run() {
   dodiff=1
   if test $dorun = 0; then
     echo "Not running program since no executable was produced." >>$baseout.log
-    str=$(printf '\r\033[%sC\033[%sm%s\e[0m' $offset 37 "-")
-    printf "%s" "$str"
+    place_chars $offset 37 "-"
     dodiff=0
   else
       echo "===== RUNNING PROGRAM =====" >>$baseout.log
@@ -324,18 +402,16 @@ do_diff() {
 
   if test $fail = 1 -o $dorun = 0 -o $dodiff = 0; then
     echo "Not testing output." >>$baseout.log
-    str=$(printf '\r\033[%sC\033[%sm%s\e[0m' $offset 37 -)
-    printf "%s" "$str"
+    place_chars $offset 37 "-"
   else
       echo "===== CHECKING OUTPUT =====" >>$baseout.log
       if diff -u "$refout" "$baseout.out" >>"$baseout.log" 2>&1; then
 	  echo "Output identical to reference" >>$baseout.log
-	  str=$(printf '\r\033[%sC\033[%sm%s\e[0m' $offset 32 "D")
+	  place_chars $offset 32 D
       else
-	  str=$(printf '\r\033[%sC\033[%sm%s\e[0m' $offset 31 "X")
+	  place_chars $offset 31 X
 	  fail=1
       fi
-      printf "%s" "$str"
   fi
 }
 
@@ -348,26 +424,37 @@ do_check() {
   refout=$3
 
   do_compile $offset
-  do_run $(expr $offset + 2)
+  offset=$(expr $offset + 2)
+  do_run $offset
+  offset=$(expr $offset + 1)
   if test -n "$refout"; then
-      do_diff $(expr $offset + 3) "$refout"
+      do_diff $offset "$refout"
   else
       if test $dodiff = 0; then
-	  str=$(printf '\r\033[%sC\033[%sm%s\e[0m' $(expr $offset + 3) 37 "-")
+	  place_chars $offset 37 "-"
       else
-	  str=$(printf '\r\033[%sC\033[%sm%s\e[0m' $(expr $offset + 3) 32 "=")
+	  place_chars $offset 32 "="
       fi
-      printf "%s" "$str"
   fi
-  #rm -rf "$outdir"
+  if test $fail = 0 -a -z "$KEEP"; then
+    rm -f "$baseout"*
+    rmdir "$outdir" >/dev/null 2>&1 || true
+  fi
   return $fail
 }
 
 do_prepdir() {
   impl=$1
   outdir=$testdir/$impl
+  if test -n "TEST_HERE"; then
+    outdir=$(echo "_$outdir"|tr '/.:' '___')
+  fi
   baseout=$outdir/$testname
-  mkdir -p "$outdir"
+
+  if ! mkdir -p "$outdir" >/dev/null 2>&1; then
+     die "$outdir: cannot create directory" 
+  fi
+
   if ! test -w "$outdir"; then
      die "$outdir: directory is not writable"
   fi
@@ -452,12 +539,10 @@ done
 
 offset=$(expr $offset + 5)
 if test $fail = 0; then
-  str=$(printf '\r\033[%sC\033[%sm%s\e[0m' $offset 37 "\o/")
+  place_chars $offset 37 "\o/"
 else
-  str=$(printf '\r\033[%sC\033[%sm%s\e[0m' $offset 31 ":(")
+  place_chars $offset 31 ":("
 fi
-printf "%s" "$str"
-
 
 echo
 exit $fail
