More tests & improvements thanks to testing.
* bin/spp: Implement local register window compression.

* bin/slt: Fix checking against reference output. Allow
implementation specifiers to indicate extra env vars to set during
testing. Change naming of output directories to a simple digit.

* lib/t-pppalpha/include/sl_support.h,
* bin/spp,
* lib/t-pppalpha/slimpl.m4: Fix delayed shared initialization.

* lib/r-mtalpha-sim: Allow extra simulator arguments via SIMARGS
variable.

* tests/0_minimal/2_args/delayshared.sl: Simplify.

* tests/div.sl: Rename to...	
* tests/1_basic/2_div/div.sl: here. Simplify to use printf.

* demo/10threads.sl: Use printf.	

* tests/1_basic/1_index/common.slh,
* tests/1_basic/1_index/defaults.sl,
* tests/1_basic/1_index/inf1.sl,
* tests/1_basic/1_index/inf2.sl,
* tests/1_basic/1_index/inf3.sl,
* tests/1_basic/1_index/inf4.sl,
* tests/1_basic/1_index/inf5.sl,
* tests/1_basic/1_index/neg1.sl,
* tests/1_basic/1_index/neg2.sl,
* tests/1_basic/1_index/neg3.sl,
* tests/1_basic/1_index/neg4.sl,
* tests/1_basic/1_index/neg5.sl,
* tests/1_basic/1_index/neg6.sl,
* tests/1_basic/1_index/neg7.sl,
* tests/1_basic/1_index/neg8.sl,
* tests/1_basic/1_index/neg9.sl,
* tests/1_basic/1_index/pos1.sl,
* tests/1_basic/1_index/pos2.sl,
* tests/1_basic/1_index/pos3.sl,
* tests/1_basic/1_index/pos4.sl,
* tests/1_basic/1_index/pos5.sl,
* tests/1_basic/1_index/pos6.sl,
* tests/1_basic/1_index/pos7.sl,
* tests/1_basic/1_index/pos8.sl,
* tests/1_basic/1_index/pos9.sl,
* tests/1_basic/2_div/div2.sl: Import from utcc.

* tests/mkalltests.sh: Remove 'x_' tests from Automake test
suite (all failures are not properly reported by all
implementations, but we want to ignore this for now and focus on
the positive features).

* demo/fibonacci.sl: Reduce N to fit execution time within 5
seconds (timeout during tests).

diff --git a/bin/slt b/bin/slt
--- a/bin/slt
+++ b/bin/slt
@@ -265,13 +265,11 @@ shift
 case $1 in
   ""|all)
     impl1=seqc
-    oimpl="ptl ppp utcx"
-    #oimpl="ptl ppp utc0 utcx"
+    set ptl ppp 'ppp:SIMARGS=-o NumProcessors=1' utcx
     ;;
   *)
     impl1=$1
     shift
-    oimpl="$@"
     ;;
 esac
 
@@ -405,6 +403,7 @@ do_diff() {
     place_chars $offset 37 "-"
   else
       echo "===== CHECKING OUTPUT =====" >>$baseout.log
+      echo "diff -u $refout $baseout.out" >>$baseout.log
       if diff -u "$refout" "$baseout.out" >>"$baseout.log" 2>&1; then
 	  echo "Output identical to reference" >>$baseout.log
 	  place_chars $offset 32 D
@@ -418,7 +417,7 @@ do_diff() {
 
 
 do_check() {
-  local offset refout
+  local offset refout b
   impl=$1
   offset=$2
   refout=$3
@@ -437,28 +436,46 @@ do_check() {
       fi
   fi
   if test $fail = 0 -a -z "$KEEP"; then
-    rm -f "$baseout"*
+    for b in "$baseout"*; do
+       if test "x$refout" != "x" -a "x$refout" != "x$b"; then
+          rm "$b"
+       fi
+    done
     rmdir "$outdir" >/dev/null 2>&1 || true
   fi
   return $fail
 }
 
-do_prepdir() {
-  impl=$1
-  outdir=$testdir/$impl
-  if test -n "$TEST_HERE"; then
-    outdir=$(echo "_$outdir"|tr '/.:' '___')
-  fi
-  baseout=$outdir/$testname
-
-  if ! mkdir -p "$outdir" >/dev/null 2>&1; then
-     die "$outdir: cannot create directory" 
-  fi
-
-  if ! test -w "$outdir"; then
-     die "$outdir: directory is not writable"
-  fi
-  rm -f "$baseout"*
+do_preptest() {
+    local vars save vn var val
+    impl=$(echo "$1" | cut -d: -f1)
+    vars=$(echo "$1" | cut -d: -f2-)
+    if test -n "$vars"; then
+	save=$IFS
+	IFS=":"
+	for vn in $vars; do
+	    var=$(echo "$vn"|cut -d= -f1)
+	    val=$(echo "$vn"|cut -d= -f2-|sed -e s/\'/\'\"\'\"\'/g)
+	    eval "export $var='$val'"
+	done
+	IFS=$save
+    fi
+    
+    outdir=$testdir/_$counter
+    counter=$(expr $counter + 1)
+    if test -n "$TEST_HERE"; then
+	outdir=$(echo "_$outdir"|tr '/.:' '___')
+    fi
+    baseout=$outdir/$testname
+    
+    if ! mkdir -p "$outdir" >/dev/null 2>&1; then
+	die "$outdir: cannot create directory" 
+    fi
+    
+    if ! test -w "$outdir"; then
+	die "$outdir: directory is not writable"
+    fi
+    rm -f "$baseout"*
 }
 
 
@@ -468,7 +485,7 @@ if stty size >/dev/null 2>&1; then
   COLUMNS=$(stty size|cut -d' ' -f2)
 fi
 COLUMNS=${COLUMNS:-80}
-nrimpl=$(echo "$oimpl"|tr ' ' '\n'|wc -l)
+nrimpl=$#
 nrcols=$(expr \( $nrimpl + 1 \) \* 5)
 remainder=$(expr $COLUMNS - $nrcols - 5)
 if test $remainder -lt 20; then remainder=20; fi
@@ -485,7 +502,8 @@ fi
 printf "%-${remainder}s" "$name"
 
 # start testing
-do_prepdir $impl1
+counter=0
+do_preptest "$impl1"
 
 bye() {
   for pid in $towait; do
@@ -501,7 +519,7 @@ fail=0
 
 signalled=0
 trap bye INT QUIT HUP TERM
-do_check $impl1 $offset &
+do_check $impl $offset &
 towait=$!
 set +e
 wait $towait
@@ -516,10 +534,11 @@ fi
 
 # Perform other tests asynchronously
 towait=
-for impl in $oimpl; do
+refout=$baseout.out
+for impl1 in "$@"; do
     offset=$(expr $offset + 5)
-    do_prepdir $impl
-    do_check $impl $offset $baseout.out &
+    do_preptest "$impl1"
+    do_check $impl $offset "$refout" &
     towait="$towait $!"
 done
 
@@ -545,6 +564,10 @@ else
 fi
 
 echo
+if test $fail = 0 -a -z "$KEEP"; then
+    rm "$refout"
+    rmdir $(dirname "$refout") >/dev/null 2>&1 || true
+fi
 exit $fail
 
 # -*- mode: shell -*-
