[sl-core] Polish the linking and loading process for LEON2-MT.
* tools/lib/leon2mt-fpga/linkrom.in: New (linker script).
* tools/lib/leon2mt-fpga/Makefile.am (nobase_sllib_DATA): List it.
* tools/lib/configure.ac: Generate it.
* tools/bin/cce.in: Use it.

* tools/lib/mt/l2mt/bootstrap.c: New. This copies the data section
to RAM.
* tools/lib/leon2mt-fpga/Makefile.am (LIBSLC_SRC): List it.
* tools/lib/mt/l2mt/slrt.s (_start): Use it.

diff --git a/slc/tools/bin/cce.in b/slc/tools/bin/cce.in
--- a/slc/tools/bin/cce.in
+++ b/slc/tools/bin/cce.in
@@ -483,7 +483,23 @@ case $slc_arch-$slc_os in
 	;;
     *-fpga)
         extra_f1flags+=(-x tls-via-gettid -x clear-local-regs)
-	slc_ldflags+=( -Wl,--section-start -Wl,.init=0 -nostdlib)
+	slc_ldflags+=(-nostdlib )
+        save_IFS=$IFS
+        IFS=:
+        found=
+        for d in $slc_libdir; do
+  	    osdir=$d/$slc_arch-$slc_os
+            if test -r "$osdir/linkrom"; then
+                found=$osdir/linkrom
+		break
+	    fi
+        done
+	if test -z "$found"; then
+	    echo "$basename: warning: linker script not found for $slc_variant-$slc_arch-$slc_os in $slc_libdir" >&2
+        else
+	    slc_ldflags+=(-Wl,-T -Wl,"$found")
+	fi
+	IFS=$save_IFS
 	;;
     host-host-hrt)
         slc_ldflags+=($PTHREAD_LIBS -static)
