[sl-core] Simplify the interface with MGSim.
The Microgrid simulator was recently modified to provide a single
binary for both COMA memory simulations. This drops the need for
separate support for `simx-alpha'.

* build-aux/mgsim.m4: Do not detect the separate executable.
* build-aux/slctests.m4: Do not require the separate executable
for ENABLE_CHECK_COMA_ZL.

* tools/lib/Makefile.am: Do not substitute the separate program.

* tools/lib/r-mt-sim.sh.in: Simplify.

* tools/lib/mt-profiles/lzcoma128_1chan,
* tools/lib/mt-profiles/lzcoma128_2chan,
* tools/lib/mt-profiles/lzcoma256_1chan,
* tools/lib/mt-profiles/lzcoma256_4chan,
* tools/lib/mt-profiles/ml-npcrypt-p1,
* tools/lib/mt-profiles/ml-npcrypt-p2,
* tools/lib/mt-profiles/ml-npcrypt-p4,
* tools/lib/mt-profiles/ml-npcrypt-p8,
* tools/lib/mt-profiles/mlcoma256_1chan,
* tools/lib/mt-profiles/mlcoma256_4chan,
* tools/lib/mt-profiles/rbm1,
* tools/lib/mt-profiles/rbm128,
* tools/lib/mt-profiles/rbm16,
* tools/lib/mt-profiles/rbm256: Update accordingly.

diff --git a/slc/tools/lib/r-mt-sim.sh.in b/slc/tools/lib/r-mt-sim.sh.in
--- a/slc/tools/lib/r-mt-sim.sh.in
+++ b/slc/tools/lib/r-mt-sim.sh.in
@@ -15,11 +15,10 @@ slc_datadir=${SLC_DATADIR:-@slc_datadir@}
 DEBUGGER=${DEBUGGER:-gdb --args}
 SIMARGS=${SIMARGS:-}
 mgsim=(${MGSIM_@ARCH@:-@MGSIM_ARCH@})
-simx=(${SIMX_@ARCH@:-@SIMX_ARCH@})
+thevar=MGSIM_@ARCH@
 nm=(${NM_MT@ARCH@_OVERRIDE:-@NM_ARCH@})
 python=${PYTHON:-@python@}
 simargs_base=()
-COMA=
 
 ##
 ## Selection of the number of cores
@@ -64,23 +63,15 @@ fi
 ## Selection of the memory system
 ##
 
-if test -n "${COMA:-}"; then
-    thevar=SIMX_@ARCH@
-    thesim=$simx
-else
-    thevar=MGSIM_@ARCH@
-    thesim=$mgsim
-fi
-
-if ! test -x "${thesim[0]}"; then
-    echo "$basename: ${thesim[0]} not found or not executable." >&2
+if ! test -x "${mgsim[0]}"; then
+    echo "$basename: ${mgsim[0]} not found or not executable." >&2
     exit 127
 else
-    bn=${thesim[0]}
+    bn=${mgsim[0]}
     bn=${bn##*/}
-    d=$(dirname "${thesim[0]}")
+    d=$(dirname "${mgsim[0]}")
     d=$(cd "$d" && pwd -P)
-    thesim[0]=$d/$bn
+    mgsim[0]=$d/$bn
 fi
 
 ##
@@ -91,10 +82,10 @@ do_debug=
 if test -n "${DEBUG:-}"; then
     simargs_base+=(-i)
     do_debug=$DEBUGGER
-    if ! test -x "${thesim[0]}.dbg"; then
-	echo "$basename: warning: ${thesim[0]}.dbg not found, using ${thesim[0]} instead." >&2
+    if ! test -x "${mgsim[0]}.dbg"; then
+	echo "$basename: warning: ${mgsim[0]}.dbg not found, using ${mgsim[0]} instead." >&2
     else
-	thesim[0]=${thesim[0]}.dbg
+	mgsim[0]=${mgsim[0]}.dbg
     fi
 fi
 
@@ -103,10 +94,10 @@ fi
 ##
 
 if test -n "${SIMGFX:-}"; then
-    if ! test -x "${thesim[0]}.gfx"; then
-	echo "$basename: warning: ${thesim[0]}.gfx not found, disabling graphical output." >&2
+    if ! test -x "${mgsim[0]}.gfx"; then
+	echo "$basename: warning: ${mgsim[0]}.gfx not found, disabling graphical output." >&2
     else    
-	thesim[0]=${thesim[0]}.gfx
+	mgsim[0]=${mgsim[0]}.gfx
 	simargs_base+=(-o GfxEnableOutput=true)
 	if test -n "${gfx_scale:-}"; then
 	    simargs_base+=(-o GfxHorizScale=${gfx_scale%,*} -o GfxVertScale=${gfx_scale#*,})
@@ -139,7 +130,7 @@ if test -z "${SLR_RECURSIVE:-}"; then
     simargs_base+=(-s "$symfile")
 fi
 
-runner_cmdline=("${thesim[@]}" \
+runner_cmdline=("${mgsim[@]}" \
     ${simargs_base+"${simargs_base[@]}"} ${SIMARGS:-} \
     -t -L7 "$datafile" -L6 "$fdatafile" -L5 "$envfile" ${1+"$@"} "$d/$b")
 
