[sl-core] Make debugging output more informative.
* tools/bin/slc.in,
* tools/bin/slr.in,
* tools/bin/slt.in,
* tools/lib/r-mt-sim.sh.in: Use absolute pathnames when printing
out program names.

diff --git a/slc/tools/lib/r-mt-sim.sh.in b/slc/tools/lib/r-mt-sim.sh.in
--- a/slc/tools/lib/r-mt-sim.sh.in
+++ b/slc/tools/lib/r-mt-sim.sh.in
@@ -69,9 +69,17 @@ if test -n "${COMA:-}"; then
 else
     thesim=$mgsim
 fi
-if ! "${thesim[@]}" --help >/dev/null 2>&1; then
-  echo "$basename: cannot find simulator (${thesim[*]})." >&2
-  exit 1
+
+if ! test -x "${thesim[0]}"; then
+  echo "$basename: ${thesim[0]} not found or not executable." >&2
+  exit 127
+else
+  d=${thesim[0]%/*}
+  if test -n "$d"; then 
+      bn=${thesim[0]##*/}
+      d=$(cd "$"; pwd -P)
+      thesim[0]=$d/$bn
+  fi
 fi
 
 ##
