[sl-core] Share runner script code between MT-Alpha/MT-Sparc.
* tools/lib/r-mtsparc-sim.sh.in: Remove.
* tools/lib/r-mtalpha-sim.sh.in: Rename to...
* tools/lib/r-mt-sim.sh.in: ...here. Change references to `alpha'
to references to `@arch@'.

* tools/lib/Makefile.am: Generate `r-mtalpha-sim.sh' and
`r-mtsparc-sim.h' from `r-mt-sim.sh.in'.

* configure.ac: Remove them from AC_CONFIG_FILES since they are
now explicitly generated by the Makefile.

diff --git a/slc/tools/lib/r-mt-sim.sh.in b/slc/tools/lib/r-mt-sim.sh.in
--- a/slc/tools/lib/r-mt-sim.sh.in
+++ b/slc/tools/lib/r-mt-sim.sh.in
@@ -1,17 +1,17 @@
 #! /bin/sh
 # $Id$
 set -eu
-MGSIM_ALPHA=${MGSIM_ALPHA:-@MGSIM_ALPHA@}
+MGSIM_@ARCH@=${MGSIM_@ARCH@:-@MGSIM_ARCH@}
 basename=${0##*/}
 program=${1:?}
 datafile=${2:?}
 fdatafile=${3:?}
 DEBUGGER=${DEBUGGER:-gdb --args}
 if test -n "${DEBUG:-}"; then
-   MGSIM_ALPHA="$MGSIM_ALPHA.dbg"
+   MGSIM_@ARCH@="$MGSIM_@ARCH@.dbg"
 fi
 if test -n "${SIMGFX:-}"; then
-   MGSIM_ALPHA="$MGSIM_ALPHA.gfx"
+   MGSIM_@ARCH@="$MGSIM_@ARCH@.gfx"
 fi
 shift
 shift
@@ -30,8 +30,8 @@ if ! test -r "$fdatafile"; then
     exit 1
 fi
 
-if ! "$MGSIM_ALPHA" --help >/dev/null 2>&1; then
-  echo "$basename: cannot find simulator (MGSIM_ALPHA=$MGSIM_ALPHA)." >&2
+if ! "$MGSIM_@ARCH@" --help >/dev/null 2>&1; then
+  echo "$basename: cannot find simulator (MGSIM_@ARCH@=$MGSIM_@ARCH@)." >&2
   exit 1
 fi
 
@@ -46,6 +46,6 @@ if test -n "${DEBUG:-}"; then
 fi
 
 if test -n "${VERBOSE:-}"; then
-    echo "$basename: running: ${RUNNER_PREFIX:-} $do_debug $MGSIM_ALPHA ${SIMARGS:-} -t ${*:-} -L16 $datafile -L17 $fdatafile $program" >&2
+    echo "$basename: running: ${RUNNER_PREFIX:-} $do_debug $MGSIM_@ARCH@ ${SIMARGS:-} -t ${*:-} -L16 $datafile -L17 $fdatafile $program" >&2
 fi  
-exec ${RUNNER_PREFIX:-} $do_debug $MGSIM_ALPHA ${SIMARGS:-} -t ${1:+"$@"} -L16 "$datafile" -L17 "$fdatafile" "$program"
+exec ${RUNNER_PREFIX:-} $do_debug $MGSIM_@ARCH@ ${SIMARGS:-} -t ${1:+"$@"} -L16 "$datafile" -L17 "$fdatafile" "$program"
